<?php
return array(
    'CorrectFollowing' => 'Please correct the following errors before proceeding:',
    'FirstName' => 'First Name',
    'FirstNameRequrired' => '"First Name" field is required.',
    'LastName' => 'Last Name',
    'LastNameRequrired' => '"Last Name" field is required.',
    'LastNameExtra' => 'Will not be added to prayer wall.',
    'EmailAddress' => 'Email address',
    'EmailAddressExtra' => 'We will contact you only if you give us permission and your email will be used for authentication to ensure that we are contacted by real person.',
    'EmailAddressRequrired' => '"Email Address" field is required.',
    'EmailAddressInvalid' => 'Inavlid email address.',
    'City' => 'City',
    'Country' => 'Country',
    'PrayerRequest' => 'Prayer request',
    'PrayerRequestRequrired' => '"Prayer request" field is required.',
    'PostPublicCheckbox' => 'Post to the public Prayer Wall (If you are posting to the prayer wall you are acknowledging that you are giving permission to post your prayer on this website)',
    'ConsentCheckbox' => 'I give consent for Society of the Divine Word to contact me via email.',
    'PolicyLabel' => 'Policy',
    'SubmitLabel' => 'Submit Your Request',
    'MessageSuccess' => 'Thanks for your submission.',
    'InvalidCaptcha' => 'Invalid captcha code.',
    'PolicyTitle' => 'We do monitor the comments and will remove posts that contain the following:',
    'PolicyPoint1' => 'Hyperlinks, ads, or other spam-like content',
    'PolicyPoint2' => 'Content we deem inappropriate, offensive, or demeaning',
    'PolicyPoint3' => 'Profanity, accusatory, inflammatory language',
    'PolicyPoint4' => 'Comments that present a specific political agenda',
    'PolicyPoint5' => 'Offensive or demeaning comments toward other cultures and religions',
    'SelectCountry' => 'Select Country'
);