<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-10-07T00:55:57-05:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      add_form.groups
 * @group     permissions
 * @namespace formidable_full
 * -----------------------------------------------------------------------------
 */
return [
    'add_form' => [
        'groups' => [
            0,
        ],
    ],
];
