version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/test.com
permissions:
  - object: /var/www/test.com
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 777
    type:
      - directory
permissions:
  - object: /var/www/test.com
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 777
    type:
      - file