version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/example.com
permissions:
    pattern: "*"
    owner: www-data
    group: www-data
    mode: 777
    type:
      - directory
  - object: /var/www
  - object: /var/www/test.com
    pattern: "*"
    owner: www-data
    group: www-data
    mode: 777
    type:
      - files