version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
permissions:
  - object: /var/www
    pattern: "*"
    owner: www-data
    group: www-data
    mode: 770
    type:
      - directory