version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/aadprt.org
permissions:
  - object: /var/www/test.com
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 777
    type:
      - directory
permissions:
  - object: /var/www/aadprt.org
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 777
    type:
      - file
hooks:
  AfterInstall:
    - location: scripts/set-permissions.sh