<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-07-31T13:31:42-05:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'America/Chicago',
];
