<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-03-18T09:08:07-05:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'America/Chicago',
];
