<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-05-15T05:42:16-05:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.5.0',
    'version_db_installed' => '20190301133300',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1552918086,
        'latest_version' => '8.5.0',
        'do_page_reindex_check' => false,
    ],
    'seo' => [
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => true,
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
        'clear' => [
            'thumbnails' => true,
        ],
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
];
