<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-06-03T16:51:21-05:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.5.1',
    'version_db_installed' => '20190301133300',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1564597901,
        'latest_version' => '8.5.1',
        'do_page_reindex_check' => false,
    ],
    'seo' => [
        'title_format' => '%2$s | %1$s',
        'title_segment_separator' => ' | ',
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => true,
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
];
