<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-02-06T01:54:31-06:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.multilingual.always_track_user_locale
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Society Of The Divine Word',
            'seo' => [
                'canonical_url' => '',
                'canonical_url_alternative' => '',
                'canonical_tag' => [
                    'enabled' => false,
                ],
            ],
            'misc' => [
                'favicon_fid' => 33,
                'iphone_home_screen_thumbnail_fid' => 31,
                'modern_tile_thumbnail_fid' => 32,
                'modern_tile_thumbnail_bgcolor' => null,
                'browser_toolbar_color' => null,
            ],
            'multilingual' => [
                'redirect_home_to_default_locale' => false,
                'default_source_locale' => 'en_US',
                'always_track_user_locale' => true,
            ],
        ],
    ],
];
