<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-11-18T17:44:48-06:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.misc.browser_toolbar_color
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'AADPRT',
            'seo' => [
                'canonical_url' => '',
                'canonical_url_alternative' => '',
                'canonical_tag' => [
                    'enabled' => false,
                ],
            ],
            'misc' => [
                'favicon_fid' => 92,
                'iphone_home_screen_thumbnail_fid' => 90,
                'modern_tile_thumbnail_fid' => 91,
                'modern_tile_thumbnail_bgcolor' => null,
                'browser_toolbar_color' => null,
            ],
        ],
    ],
];
