<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-11-19T14:54:16-06:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      ceb.John
 * @group     card
 * @namespace mass_enrollment
 * -----------------------------------------------------------------------------
 */
return [
    'en' => [
        'MissionMassLeague' => 'Mission Mass League',
        'MissionariesDivineWord' => 'Missionaries of the Divine Word',
        'PrayerMessage' => 'will be remembered PERPETUALLY in the seven Holy Masses which are said daily for the members of the Mission Mass League and in all the prayers and good works of the Missionaries of the Divine Word.',
        'ForGodLove' => 'For God so loved the world, that he
gave his only Son, that whoever
believes in him should not perish
but have eternal life',
        'John' => 'John 3,16',
    ],
    'pl' => [
        'MissionMassLeague' => 'Misyjne Msze Wieczyste',
        'MissionariesDivineWord' => 'Misjonarzy Słowa Bożego',
        'PrayerMessage' => 'oraz wszyscy zapisani do Misyjnych Mszy Wieczystych będą wspominani NA ZAWSZE, podczas 7 Mszy św. odprawianych codziennie w intencji członków Misyjnych Mszy Wieczystych i pamiętani we wszystkich modlitwach Misjonarzy Słowa Bożego.',
        'ForGodLove' => 'Albowiem tak Bóg umiłował świat, że Syna swego jednorodzonego dał, aby każdy, kto weń wierzy, nie zginął, ale miał żywot wieczny',
        'John' => 'Jan 3,16',
    ],
    'es' => [
        'MissionMassLeague' => 'ALIANZA MISIONERA DE MISAS',
        'MissionariesDivineWord' => 'Misioneros del Verbo Divino',
        'PrayerMessage' => 'y todos los miembros de la Alianza Misionera de Misas, serán recordados PERPETUAMENTE en siete Santas Misas celebradas diariamente por todos los inscritos en la Alianza y presentes en todas las oraciones de los Misioneros del Verbo Divino.',
        'ForGodLove' => 'Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna',
        'John' => 'Juan 3,16',
    ],
    'pt' => [
        'MissionMassLeague' => 'LIGA MISSIONÁRIA DAS MISSAS PERPÉTUAS',
        'MissionariesDivineWord' => 'Missionários do Verbo Divino',
        'PrayerMessage' => 'e todos os membros da Liga Missionária das Missas Perpétuas serão lembrados PERPETUAMENTE em sete Santas Missas celebradas diariamente por todos os inscritos na Liga e presentes em todas orações dos Missionários do Verbo Divino.',
        'ForGodLove' => 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna',
        'John' => 'João 3,16',
    ],
    'fr' => [
        'MissionMassLeague' => 'LA LIGUE DES MESSES MISSIONNAIRES',
        'MissionariesDivineWord' => 'Missionnaires du Verbe Divin',
        'PrayerMessage' => 'et tous les membres engagés dans la Ligue des Messes Missionnaires feront l\'objet de prières À PERPÉTUITÉ pendant sept Saintes Messes dites quotidiennement en faveur des membres de la Ligue et les Missionnaires du Verbe Divin se souviendront d\'eux dans toutes leurs prières.',
        'ForGodLove' => 'For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life',
        'John' => 'John 3,16',
    ],
    'de' => [
        'MissionMassLeague' => 'MISSIONSMESSBUND',
        'MissionariesDivineWord' => 'der Steyler Missionare',
        'PrayerMessage' => 'STÄNDIG, zusammen mit allen Mitgliedern des Missionsmessbundes, in sieben Heiligen Messen eingeschlossen, die täglich für alle im Missionsmessbund eingeschriebenen Mitgliedern zelebriert werden. Ebenso sind sie gegenwärtig in allen Gebeten der Steyler Missionare.',
        'ForGodLove' => 'For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life',
        'John' => 'John 3,16',
    ],
    'hr' => [
        'MissionMassLeague' => 'MISIJSKA MISNA LIGA',
        'MissionariesDivineWord' => 'Družba Božje Riječi',
        'PrayerMessage' => 'u zajedništvu s ostalim članovima Misijske Misne Lige, trajno ce biti spominjani kroz sedam svetih Misa koje se dnevno slave za sve članove Lige te u svim molitvama Misionara Družbe Božje Riječi.',
        'ForGodLove' => 'For God so loved the world, that he
gave his only Son, that whoever
believes in him should not perish
but have eternal life',
        'John' => 'John 3,16',
    ],
    'hu' => [
        'MissionMassLeague' => 'MISSZIÓS MISESZÖVETSÉG',
        'MissionariesDivineWord' => 'Isteni Ige Társasága - Verbiták',
        'PrayerMessage' => 'és mindazok, akiket felvettünk a Missziós Miseszövetségbe, örökre részesülni fognak a Miseszövetség tagjaiért mondott napi hét szentmise értékében és a verbiták imádságainak gyümölcsében.',
        'ForGodLove' => 'For God so loved the world, that he
gave his only Son, that whoever
believes in him should not perish
but have eternal life',
        'John' => 'John 3,16',
    ],
    'it' => [
        'MissionMassLeague' => 'LEGA MISSIONARIA DELLA MESSA',
        'MissionariesDivineWord' => 'Missionari del Verbo Divino',
        'PrayerMessage' => 'insieme a tutti i soci iscritti nella Lega Missionaria della Messa sarà ricordato PERPETUAMENTE in sette Sante Messe che si dice tutti i giorni per i membri della Lega e sarà considerato in tutte le preghiere dei Missionari del Verbo Divino.',
        'ForGodLove' => 'For God so loved the world, that he
gave his only Son, that whoever
believes in him should not perish
but have eternal life',
        'John' => 'John 3,16',
    ],
    'lt' => [
        'MissionMassLeague' => 'MISIONIERIŲ MIŠIU LYGA',
        'MissionariesDivineWord' => 'Missionaries of the Divine Word',
        'PrayerMessage' => 'kartu su visais Misionierių šv. mišių lygos nariais jie bus AMŽINAI minimi septyneriose šv. Mišiose, kasdien atnašaujamose už Lygos narius ir visose Dievo žodžio misionierių maldose.',
        'ForGodLove' => 'For God so loved the world, that he
gave his only Son, that whoever
believes in him should not perish
but have eternal life',
        'John' => 'John 3,16',
    ],
    'sk' => [
        'MissionMassLeague' => 'MISIJNÝ OMŠOVÝ SPOLOK',
        'MissionariesDivineWord' => 'Misionári Spoločnosti Božieho Slova',
        'PrayerMessage' => 'má spolu s ostatnými členmi Misijného omšového spolku účasť na dobrodeniach a požehnaní siedmich svätých omší, ktoré Misionári Spoločnosti Božieho Slova denne slúžia na rozličných miestach sveta za všetkých členov Misijného omšového spolku a je zahrnutý do modlitieb Misionárov Spoločnosti Božieho Slova, ktorí sa s vďačnosťou modlia za svojich dobrodincov.',
        'ForGodLove' => 'For God so loved the world, that he
gave his only Son, that whoever
believes in him should not perish
but have eternal life',
        'John' => 'John 3,16',
    ],
    'vi' => [
        'MissionMassLeague' => 'HỘI THÁNH LỄ TRUYỀN GIÁO',
        'MissionariesDivineWord' => 'Dòng Truyền Giáo Ngôi Lời',
        'PrayerMessage' => 'và tất cả những người đã ghi tên vào Hội Thánh Lễ Truyền Giáo sẽ được nhớ đến vĩnh viễn trong 7 Thánh Lễ dâng hằng ngày cho các thành viên của Hội và trong tất cả kinh nguyện và việc lành của các Vị Truyền Giáo Ngôi Lời.',
        'ForGodLove' => 'For God so loved the world, that he
gave his only Son, that whoever
believes in him should not perish
but have eternal life',
        'John' => 'John 3,16',
    ],
    'ceb' => [
        'MissionMassLeague' => 'KATILINGBANONG HALAD-PAMISA ALANG SA MISYON',
        'MissionariesDivineWord' => 'uban sa mga Misyonero sa Balaang Pulong (SVD)',
        'PrayerMessage' => 'ug ang tanang miyembro nga nahilakip sa tala sa Halad-Pamisa alang sa Misyon among hinumduman kanunay sa pito ka Balaang Misa nga saulogon matag adlaw ug iapil sa mga pag-ampo sa tanang Misyonero sa Balaang Pulong (SVD) sa tibuok kalibutan.',
        'ForGodLove' => 'For God so loved the world, that he
gave his only Son, that whoever
believes in him should not perish
but have eternal life',
        'John' => 'John 3,16',
    ],
    'tl' => [
        'MissionMassLeague' => 'ALAY-ALAALA AT PAMISA PARA SA MISYON',
        'MissionariesDivineWord' => 'kaisa sa mga Misyonero ng Banal na Diwa (SVD)',
        'PrayerMessage' => 'at ang lahat ng kaibigan at kapamilya na kasali sa Alay-Alaala\'t Pamisa para sa Misyon ay palagi naming inaalala sa pitong banal na misa na ipinagdiriwang araw-araw, at isinasama namin sa mga intensyon at panalangin ng lahat na Misyonero ng Banal na Diwa sa buong mundo.',
        'ForGodLove' => 'For God so loved the world, that he
gave his only Son, that whoever
believes in him should not perish
but have eternal life',
        'John' => 'John 3,16',
    ],
    'ilo' => [
        'MissionMassLeague' => 'LIGA TI MISYON TI MISA',
        'MissionariesDivineWord' => 'Misyonaryo ti Nasantuan nga Sarita',
        'PrayerMessage' => 'ken amin nga miembro a nakalista iti Mission Mass League ket mailagip dantu nga agnanayon iti pito a nasantuan a misa nga maaramid para kadagiti miembro iti Liga, ken mailagip latta iti amin a karkararag iti Divine Word Missionaries.',
        'ForGodLove' => 'For God so loved the world, that he
gave his only Son, that whoever
believes in him should not perish
but have eternal life',
        'John' => 'John 3,16',
    ],
    'ko' => [
        'MissionMassLeague' => '선교미사연합회',
        'MissionariesDivineWord' => '말씀의 선교 수도회',
        'PrayerMessage' => '그리고 선교미사연합회에 등록된 모든 사람들은 연합회 구성원들을 위하여 매일 봉헌되는 7번의 성스러운 미사를 통하여 지속적으로 기억될 것이며, 또한 모든 기도 청원자들과 말씀의 선교 수도회의 훌륭한 사명 안에서도 영원히 기억될 것입니다.',
        'ForGodLove' => 'For God so loved the world, that he
gave his only Son, that whoever
believes in him should not perish
but have eternal life',
        'John' => 'John 3,16',
    ],
];
