<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-10-08T12:27:02+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      ko
 * @group     cardlanguages
 * @namespace mass_enrollment
 * -----------------------------------------------------------------------------
 */
return [
    'en' => 'English',
    'pl' => 'Polish',
    'es' => 'Spanish',
    'pt' => 'Portuguese',
    'fr' => 'French',
    'de' => 'German',
    'hr' => 'Croatian',
    'hu' => 'Hungarian',
    'it' => 'Italian',
    'lt' => 'Lithuanian',
    'sk' => 'Slovak',
    'vi' => 'Vietnamese',
    'ceb' => 'Cebuano',
    'tl' => 'Tagalog',
    'ilo' => 'Iloko',
    'ko' => 'Korean',
];
