<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-01-14T10:35:59-06:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      ko
 * @group     carddateformat
 * @namespace mass_enrollment
 * -----------------------------------------------------------------------------
 */
return [
    'en' => 'M/D/Y',
    'pl' => 'M/D/Y',
    'es' => 'M/D/Y',
    'pt' => 'M/D/Y',
    'fr' => 'M/D/Y',
    'de' => 'M/D/Y',
    'hr' => 'M/D/Y',
    'hu' => 'M/D/Y',
    'it' => 'M/D/Y',
    'lt' => 'M/D/Y',
    'sk' => 'M/D/Y',
    'vi' => 'M/D/Y',
    'ceb' => 'M/D/Y',
    'tl' => 'M/D/Y',
    'ilo' => 'M/D/Y',
    'ko' => 'M/D/Y',
];
