<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-05-14T14:14:35-05:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      emails.sp.NotifyEmailTemp
 * @group     custom
 * @namespace mass_enrollment
 * -----------------------------------------------------------------------------
 */
return [
    'emails' => [
        'Default' => [
            'AdminEmail' => 'divinewordgifts@uscsvd.org',
            'FromEmail' => 'divinewordgifts@uscsvd.org',
            'FromName' => 'Society of the Divine Word',
            'UserEmailSub' => 'Thank You For Your Donation',
            'UserEmailTemplate' => '<div>Dear&nbsp;{first_name},</div>

<div>On behalf of the missionaries of the Society of the Divine Word and the people of faith they serve, I thank you for your gift of&nbsp;<strong>{amount}</strong>.</div>

<div>Your confirmation number is <strong>{gift_id}</strong> and the details of your request follow:</div>

<div>-----------------------</div>

<div>
<div><strong>Requester: </strong>{first_name} {last_name}</div>

<div><strong>Donation for: </strong>{name_of_form}</div>

<div><strong>Intention: </strong>{intention}</div>

<div><strong>Card Language: </strong>{card_lang}&nbsp;</div>

<div><strong>Folder Color: </strong>{folder_color}</div>

<div><strong>Folder Image: </strong>{folder_image}</div>

<div><strong>Living or Deceased:&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Requested By:&nbsp;</strong>{requested_by}</div>

<div><strong>Notification send to:</strong> {notify_first_name}&nbsp;{notify_last_name}</div>

<div><strong>Certificate International Shipping:</strong> {international_shipping}</div>

<div><strong>E-Card Link:</strong>&nbsp;{pe_e_card}</div>
</div>

<div>------------------------</div>

<div>This gift will be directed as you requested. if you did not specify a particular mission or purpose, we will share your gift with many people, especially:</div>

<ul>
	<li>
	<div>the poor and marginalized whom we serve</div>
	</li>
	<li>
	<div>seminarians whose educations we fund</div>
	</li>
	<li>
	<div>retired missionaries who have devoted their lives to spreading the Good News of God&#39;s love for all.</div>
	</li>
</ul>

<div>Thank you for making your donation electronically. By doing so, you have helped to preserve the integrity of God&#39;s creation and also have helped us lower our costs so that we can send more funds to those in need. If you haven&#39;t already done so, we invite you to bookmark our website: www.divinewordgifts.org.</div>

<div>If you have questions, you can reach us at (800)-775-0030 or divinewordgifts@uscsvd.org</div>

<div>May God reward you for your generosity.</div>

<div>&nbsp;</div>

<div>With my priestly blessing, in the Divine Word,</div>

<div><img alt="engsign.jpg" src="http://divinewordgifts.informaticsinc.com/download_file/view_inline/84" style="height: 52px; width: 70px;" /></div>

<div><em>Father Janusz (John) Horowski SVD</em></div>
',
            'AdminEmailSub' => 'RECEIPT - New Donation Has Been Added',
            'AdminEmailTemp' => '<p>We have recieved online donation with the following information:&nbsp;</p>

<p>-------------------------</p>

<div><strong>Requester: </strong>{first_name} {last_name}</div>

<div><strong>Donation for: </strong>{name_of_form}</div>

<div><strong>Intention: </strong>{intention}</div>

<div><strong>Card Language: </strong>{card_lang}&nbsp;</div>

<div><strong>Folder Color: </strong>{folder_color}</div>

<div><strong>Folder Image: </strong>{folder_image}</div>

<div><strong>Living or Deceased:&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Requested By:&nbsp;</strong>{requested_by}</div>

<div><strong>Notification send to:</strong> {notify_first_name}&nbsp;{notify_last_name}</div>

<div><strong>Certificate International Shipping:</strong> {international_shipping}</div>

<div><strong>PE E-Card Link:</strong>&nbsp;{pe_e_card}</div>

<p>-------------------------</p>

<p>&nbsp;</p>
',
            'NotifyEmailSub' => 'We received donation and we were asked to notify you',
            'NotifyEmailTemp' => '<div>Dear&nbsp;{first_name},</div>

<div>On behalf of the priests and brothers of the Society of the Divine Word, and people of faith to whom they minister, I am happy to inform you that we have received a donation for:</div>

<div>-----------------------</div>

<div>
<div>&nbsp;</div>

<div><strong>Requester: </strong>{first_name} {last_name}</div>

<div><strong>Donation for: </strong>{name_of_form}</div>

<div><strong>Intention: </strong>{intention}</div>

<div><strong>Card Language: </strong>{card_lang}&nbsp;</div>

<div><strong>Folder Color: </strong>{folder_color}</div>

<div><strong>Folder Image: </strong>{folder_image}</div>

<div><strong>Living or Deceased:&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Requested By:&nbsp;</strong>{requested_by}</div>

<div><strong>Notification send to:</strong> {notify_first_name}&nbsp;{notify_last_name}</div>

<div><strong>Certificate International Shipping:</strong> {international_shipping}</div>

<div><strong>E-Card Link:</strong>&nbsp;{pe_e_card}</div>
</div>

<div>------------------------</div>

<p>Moved by the same spirit that inspired St. Arnold Janssen to found the Divine Word Missionaries, we seek to complement his efforts of spreading the Word of God, collaborating in the formation of leaders, and establishing vibrant Christian communities. We are a religious missionary congregation of more than 6,000 priests and brothers working in almost 80 countries.<b>&nbsp;</b></p>

<p><b>Remember us in your prayers!</b></p>
',
        ],
        'en' => [
            'AdminEmail' => 'suyash12may96@gmail.com',
            'FromEmail' => 'divinewordgifts@uscsvd.org',
            'FromName' => 'Society of the Divine Word',
            'UserEmailSub' => 'Thank You For Your Donation',
            'UserEmailTemplate' => '<div>Dear&nbsp;{first_name},</div>

<div>On behalf of the missionaries of the Society of the Divine Word and the people of faith they serve, I thank you for your gift of&nbsp;<strong>{amount}</strong>.</div>

<div>Your confirmation number is <strong>{gift_id}</strong> and the details of your request follow:</div>

<div>-----------------------</div>

<div><strong>Requester: </strong>{first_name} {last_name}</div>

<div><strong>Donation for: </strong>{name_of_form}</div>

<div><strong>Intention: </strong>{intention}</div>

<div><strong>Card Language: </strong>{card_lang}&nbsp;</div>

<div><strong>Folder Color: </strong>{folder_color}</div>

<div><strong>Folder Image: </strong>{folder_image}</div>

<div><strong>Living or Deceased:&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Requested By:&nbsp;</strong>{requested_by}</div>

<div><strong>Notification send to:</strong> {notify_first_name}&nbsp;{notify_last_name}</div>

<div><strong>Certificate International Shipping:</strong> {international_shipping}</div>

<div><strong>E-Card Link:</strong>&nbsp;{pe_e_card}</div>

<div>------------------------</div>

<div>This gift will be directed as you requested. if you did not specify a particular mission or purpose, we will share your gift with many people, especially:</div>

<ul>
	<li>
	<div>the poor and marginalized whom we serve</div>
	</li>
	<li>
	<div>seminarians whose educations we fund</div>
	</li>
	<li>
	<div>retired missionaries who have devoted their lives to spreading the Good News of God&#39;s love for all.</div>
	</li>
</ul>

<div>Thank you for making your donation electronically. By doing so, you have helped to preserve the integrity of God&#39;s creation and also have helped us lower our costs so that we can send more funds to those in need. If you haven&#39;t already done so, we invite you to bookmark our website: www.divinewordgifts.org.</div>

<div>If you have questions, you can reach us at (800)-775-0030 or development@uscsvd.org</div>

<div>May God reward you for your generosity.</div>

<div>With my priestly blessing, in the Divine Word,</div>

<div><img alt="engsign.jpg" src="http://divinewordgifts.informaticsinc.com/download_file/view_inline/84" style="height: 55px; width: 70px;" /></div>

<div><em>Father Janusz (John) Horowski SVD</em></div>
',
            'AdminEmailSub' => 'Receipt English - New Donation Has Been Added',
            'AdminEmailTemp' => '<p>We have received online donation with the following information:&nbsp;</p>

<div>-------------------------</div>

<div><strong>Requester: </strong>{first_name} {last_name}</div>

<div><strong>Donation for: </strong>{name_of_form}</div>

<div><strong>Intention: </strong>{intention}</div>

<div><strong>Card Language: </strong>{card_lang}&nbsp;</div>

<div><strong>Folder Color: </strong>{folder_color}</div>

<div><strong>Folder Image: </strong>{folder_image}</div>

<div><strong>Living or Deceased:&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Requested By:&nbsp;</strong>{requested_by}</div>

<div><strong>Notification send to:</strong> {notify_first_name}&nbsp;{notify_last_name}</div>

<div><strong>Certificate International Shipping:</strong> {international_shipping}</div>

<div><strong>E-Card Link:</strong>&nbsp;{pe_e_card}</div>

<div>-------------------------</div>
',
            'NotifyEmailSub' => 'We received donation and we were asked to notify you',
            'NotifyEmailTemp' => '<div>Dear&nbsp;{first_name},</div>

<div>On behalf of the priests and brothers of the Society of the Divine Word, and people of faith to whom they minister, I am happy to inform you that we have received a donation for:</div>

<div>-----------------------</div>

<div><strong>Requester: </strong>{first_name} {last_name}</div>

<div><strong>Donation for: </strong>{name_of_form}</div>

<div><strong>Intention: </strong>{intention}</div>

<div><strong>Card Language: </strong>{card_lang}&nbsp;</div>

<div><strong>Folder Color: </strong>{folder_color}</div>

<div><strong>Folder Image: </strong>{folder_image}</div>

<div><strong>Living or Deceased:&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Requested By:&nbsp;</strong>{requested_by}</div>

<div><strong>Notification send to:</strong> {notify_first_name}&nbsp;{notify_last_name}</div>

<div><strong>Certificate International Shipping:</strong> {international_shipping}</div>

<div><strong>E-Card Link:</strong>&nbsp;{pe_e_card}</div>

<div>&nbsp;</div>

<div>------------------------</div>

<div>Moved by the same spirit that inspired St. Arnold Janssen to found the Divine Word Missionaries, we seek to complement his efforts of spreading the Word of God, collaborating in the formation of leaders, and establishing vibrant Christian communities. We are a religious missionary congregation of more than 6,000 priests and brothers working in almost 80 countries.<b>&nbsp;</b></div>

<div><b>Remember us in your prayers!</b></div>

<div>&nbsp;</div>
',
        ],
        'pl' => [
            'AdminEmail' => 'MisjonarzeWerbisci@uscsvd.org',
            'FromEmail' => 'MisjonarzeWerbisci@uscsvd.org',
            'FromName' => 'Misjonarze Słowa Bożego – Werbiści',
            'UserEmailSub' => 'Bóg Zapłać Za Wsparcie Misjonarzy Werbistów',
            'UserEmailTemplate' => '<div>
<div class="MsoNoSpacing"><span lang="PL" style="mso-ansi-language:PL">Drogi(a) {first_name},<o:p></o:p></span></div>

<div class="MsoNoSpacing"><span lang="PL" style="mso-ansi-language:PL">W imieniu kapłan&oacute;w i braci ze Zgromadzenia Słowa Bożego (Misjonarzy Werbist&oacute;w) i wiernych, pośr&oacute;d kt&oacute;rych wykonujemy naszą misjonarską posługę, pragnę złożyć serdeczne &quot;B&oacute;g Zapłać&quot; za ofiarę <strong>{amount}</strong>.<o:p></o:p></span></div>

<div class="MsoNoSpacing"><span lang="PL" style="mso-ansi-language:PL">Tw&oacute;j numer potwierdzenia to <strong>{gift_id}</strong> a szczeg&oacute;ły poniżej:<o:p></o:p></span></div>
</div>

<div>-----------------------</div>

<div>
<div><strong>Ofiarodawca: </strong>{first_name} {last_name}</div>

<div><strong>Ofiara na: </strong>{name_of_form}</div>

<div><strong>Intencja(e): </strong>{intention}</div>

<div><strong>Język wpisu: </strong>{card_lang}&nbsp;</div>

<div><strong>Kolor oprawy: </strong>{folder_color}</div>

<div><strong>Obrazek: </strong>{folder_image}</div>

<div><strong>Za Żyjących/Zmarłych:&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Wpisu dokonuje:&nbsp;</strong>{requested_by}</div>

<div><strong>Zawiadominie otrzyma:</strong> {notify_first_name}&nbsp;{notify_last_name}</div>

<div><strong>Wysyłka międzynarodowa certyfikatu:</strong> {international_shipping}</div>

<div><strong>Link do certyfikatu elektronicznego:</strong>&nbsp;{pe_e_card}</div>
</div>

<div>------------------------</div>

<div>
<div class="MsoNoSpacing"><span lang="PL" style="mso-ansi-language:PL">Zam&oacute;wienie zostanie zrealizowane zgodnie z Twoją prośbą, a ofiara kt&oacute;rą złożyłeś będzie pomocą dla:<o:p></o:p></span></div>

<div class="MsoNoSpacing"><span lang="PL" style="mso-ansi-language:PL">&bull; ubogich i zmarginalizowanych, wśr&oacute;d kt&oacute;rych służymy<o:p></o:p></span></div>

<div class="MsoNoSpacing"><span lang="PL" style="mso-ansi-language:PL">&bull; seminarzyst&oacute;w, kt&oacute;rych kształcimy na przyszłych misjonarzy<o:p></o:p></span></div>

<div class="MsoNoSpacing"><span lang="PL" style="mso-ansi-language:PL">&bull; misjonarzy głoszących Ewangelię w najdalszych zakątach świata<o:p></o:p></span></div>

<div class="MsoNoSpacing"><span lang="PL" style="mso-ansi-language:PL">&bull; emerytowanych misjonarzy, kt&oacute;rzy poświęcili swoje życie na głoszenie Dobrej Nowiny<o:p></o:p></span></div>

<div class="MsoNoSpacing"><span lang="PL" style="mso-ansi-language:PL"><o:p>&nbsp;</o:p></span></div>

<div class="MsoNoSpacing"><span lang="PL" style="mso-ansi-language:PL">Jestem wdzięczny za przekazanie ofiary drogą elektroniczną. Pomoże nam to obniżyć koszty a tym samym zwiększyć fundusze dla potrzebujących.<o:p></o:p></span></div>

<div class="MsoNoSpacing"><span lang="PL" style="mso-ansi-language:PL">Zapraszam do umieszczenia naszej strony internetowej www.divinewordgifts.org w &bdquo;ulubionych&rdquo; (bookmarks), aby w przyszłości łatwiej nas znaleźć.<o:p></o:p></span></div>

<div class="MsoNoSpacing"><span lang="PL" style="mso-ansi-language:PL">Jeśli masz pytania lub wątpliwości skontaktuj się z nami pod numerem 847-753-7422 lub wyślij emaila na adres: misjonarzewerbisci@uscsvd.org<o:p></o:p><o:p> </o:p></span></div>

<div class="MsoNoSpacing"><span lang="PL" style="mso-ansi-language:PL"><o:p>&nbsp;</o:p></span></div>

<div class="MsoNoSpacing"><strong><span lang="PL" style="mso-ansi-language:PL">Serdeczne B&oacute;g zapłać za Twoją ofiarę!</span></strong><span lang="PL" style="mso-ansi-language:PL"><o:p></o:p></span></div>

<div class="MsoNoSpacing"><span lang="PL" style="mso-ansi-language:PL"><o:p>&nbsp;</o:p></span></div>

<div class="MsoNoSpacing"><span lang="PL" style="mso-ansi-language:PL">Z kapłańskim błogosławieństwem, w miłości Słowa Bożego,<o:p></o:p></span></div>
</div>

<div><img alt="polsign.jpg" src="http://divinewordgifts.informaticsinc.com/download_file/view_inline/88" style="width: 70px; height: 39px;" /></div>

<div><em>Ks. Janusz Horowski, SVD</em></div>
',
            'AdminEmailSub' => 'Receipt Polish - New Donation Has Been Added',
            'AdminEmailTemp' => '<p>We have received online donation with the following information:&nbsp;</p>

<div>-------------------------</div>

<div><strong>Requester: </strong>{first_name} {last_name}</div>

<div><strong>Donation for: </strong>{name_of_form}</div>

<div><strong>Intention: </strong>{intention}</div>

<div><strong>Card Language: </strong>{card_lang}&nbsp;</div>

<div><strong>Folder Color: </strong>{folder_color}</div>

<div><strong>Folder Image: </strong>{folder_image}</div>

<div><strong>Living or Deceased:&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Requested By:&nbsp;</strong>{requested_by}</div>

<div><strong>Notification send to:</strong> {notify_first_name}&nbsp;{notify_last_name}</div>

<div><strong>Certificate International Shipping:</strong> {international_shipping}</div>

<div><strong>E-Card Link:</strong>&nbsp;{pe_e_card}</div>

<div>-------------------------</div>
',
            'NotifyEmailSub' => 'Otrzymaliśmy ofiarę z prośbą, aby Cię o tym powiadomić',
            'NotifyEmailTemp' => '<div>Drogi(a) {first_name},</div>

<div>
<p class="MsoNormal"><span lang="PL" style="mso-ansi-language:PL;mso-no-proof:yes">W imieniu kapłan&oacute;w i braci ze Zgromadzenia Słowa Bożego i wiernych, pośr&oacute;d, kt&oacute;rych wykonujemy naszą misyjną posługę, miło mi poinformować, że otrzymaliśmy ofiarę na cele Zgromadzenia, związaną z prośbą o:<o:p></o:p></span></p>
</div>

<div>-----------------------</div>

<div>
<div><strong>Ofiarodawca: </strong>{first_name} {last_name}</div>

<div><strong>Ofiara na: </strong>{name_of_form}</div>

<div><strong>Intencja(e): </strong>{intention}</div>

<div><strong>Język wpisu: </strong>{card_lang}&nbsp;</div>

<div><strong>Kolor oprawy: </strong>{folder_color}</div>

<div><strong>Obrazek: </strong>{folder_image}</div>

<div><strong>Za Żyjących/Zmarłych:&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Wpisu dokonuje:&nbsp;</strong>{requested_by}</div>

<div><strong>Zawiadominie otrzyma:</strong> {notify_first_name}&nbsp;{notify_last_name}</div>

<div><strong>Wysyłka międzynarodowa certyfikatu:</strong> {international_shipping}</div>

<div><strong>Link do certyfikatu elektronicznego:</strong>&nbsp;{pe_e_card}</div>
</div>

<div>------------------------</div>

<div>
<div class="MsoNormal"><span lang="PL" style="mso-ansi-language:PL;mso-no-proof:yes">Zgromadzenie Słowa Bożego jest międzynarodowym Rzymsko-Katolickim zgromadzeniem misyjnym. Nasi misjonarze, księża i bracia, w liczbie ponad 6000 prowadzą ewangelizacyjną pracę w prawie 80 krajach. Staramy się być wierni wezwaniu Chrystusa &quot;Idźcie na cały świat i głoście Ewangelię wszelkiemu stworzeniu...&quot; i wypełniać to wezwanie poprzez pracę pastoralną, sakramentalną i charytatywną.<o:p></o:p></span></div>

<div class="MsoNormal"><b style="mso-bidi-font-weight:normal"><span lang="PL" style="mso-ansi-language:PL;mso-no-proof:yes">Pamiętaj o nas w swoich modlitwach!</span></b></div>

<div class="MsoNormal">&nbsp;</div>

<div><o:p></o:p>Z kapłańskim błogosławieństwem,<o:p></o:p></div>
</div>

<div><img alt="polsign.jpg" src="http://divinewordgifts.informaticsinc.com/download_file/view_inline/88" style="width: 70px; height: 39px;" /></div>

<div><em>Ks. Janusz Horowski SVD</em></div>
',
        ],
        'pt' => [
            'AdminEmail' => 'divinewordgifts@uscsvd.org',
            'FromEmail' => 'divinewordgifts@uscsvd.org',
            'FromName' => 'Missionários do Verbo Divino',
            'UserEmailSub' => 'Muito Obrigado Pela Doação',
            'UserEmailTemplate' => '<div>Prezado(a) {first_name},</div>

<div>Em nome dos mission&aacute;rios da Congrega&ccedil;&atilde;o do Verbo Divino e das pessoas de f&eacute; que eles servem, eu agrade&ccedil;o-lhe a sua oferta de <strong>{amount}.</strong></div>

<div>Seu n&uacute;mero de confirma&ccedil;&atilde;o &eacute; <strong> {gift_id}</strong> e os detalhes do pedido est&atilde;o abaixo:</div>

<div>-----------------------</div>

<div><strong>Doador: </strong>{first_name} {last_name}</div>

<div><strong>Doa&ccedil;&atilde;o para: </strong>{name_of_form}</div>

<div><strong>Inten&ccedil;&atilde;o:&nbsp;​</strong>​​{intention}</div>

<div><strong>Idioma: </strong>{card_lang}&nbsp;</div>

<div><strong>Cor da pasta: </strong>{folder_color}</div>

<div><strong>Imagem: </strong>{folder_image}</div>

<div><strong>Por vivos our falecidos:&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Solicitado por:&nbsp;</strong>{requested_by}</div>

<div><strong>Notifica&ccedil;&atilde;o para​​​​:</strong> {notify_first_name}&nbsp;{notify_last_name}</div>

<div><strong>Remessa internacional de certificado:</strong> {international_shipping}</div>

<div><strong>E-Card Link:</strong>&nbsp;{pe_e_card}</div>

<div>------------------------</div>

<div>
<div>Sua oferta ser&aacute; processada como solicitou. Se n&atilde;o especificou qualquer miss&atilde;o ou finalidade, partilharemos a sua oferta com muitas pessoas, especialmente com: <o:p></o:p></div>

<div>&bull; Os pobres e marginalizados que servimos;<o:p></o:p></div>

<div>&bull; Os seminaristas cuja educa&ccedil;&atilde;o financiamos;<o:p></o:p></div>

<div>&bull; Os mission&aacute;rios aposentados que dedicaram as suas vidas a divulgarem a Boa Nova do amor de Deus para todos. <o:p></o:p></div>

<div><o:p>&nbsp;</o:p></div>

<div>Obrigado por fazer a sua doa&ccedil;&atilde;o eletronicamente. Ao faz&ecirc;-lo, contribuiu para preservar a integridade da cria&ccedil;&atilde;o de Deus e ajudou-nos a reduzir os nossos custos e a enviar mais fundos para os necessitados. Se ainda n&atilde;o o fez, convidamo-lo a marcar o nosso website nos seus favoritos: www.divinewordgifts.org <o:p></o:p></div>

<div>Se precisar de algum esclarecimento, contacte-nos pelo (847) 205-2300 ou verbodivino@uscsvd.org <o:p></o:p></div>

<div><o:p>&nbsp;</o:p></div>

<div><strong>Possa Deus recompensar a sua generosidade! </strong><o:p></o:p></div>

<div><o:p>&nbsp;</o:p></div>

<div>Com uma b&ecirc;n&ccedil;&atilde;o sacerdotal, no amor do Verbo Divino,<o:p></o:p></div>
</div>

<div><img alt="portsign.jpg" src="http://divinewordgifts.informaticsinc.com/download_file/view_inline/87" style="width: 70px; height: 62px;" /></div>

<div>
<div><em>Pe. Janusz (Jo&atilde;o) Horowski, SVD</em><o:p></o:p></div>
</div>
',
            'AdminEmailSub' => 'Receipt Portuguese - New Donation Has Been Added',
            'AdminEmailTemp' => '<p>We have received online donation with the following information:&nbsp;</p>

<div>-------------------------</div>

<div><strong>Requester: </strong>{first_name} {last_name}</div>

<div><strong>Donation for: </strong>{name_of_form}</div>

<div><strong>Intention: </strong>{intention}</div>

<div><strong>Card Language: </strong>{card_lang}&nbsp;</div>

<div><strong>Folder Color: </strong>{folder_color}</div>

<div><strong>Folder Image: </strong>{folder_image}</div>

<div><strong>Living or Deceased:&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Requested By:&nbsp;</strong>{requested_by}</div>

<div><strong>Notification send to:</strong> {notify_first_name}&nbsp;{notify_last_name}</div>

<div><strong>Certificate International Shipping:</strong> {international_shipping}</div>

<div><strong>E-Card Link:</strong>&nbsp;{pe_e_card}</div>

<div>-------------------------</div>
',
            'NotifyEmailSub' => 'Recebemos a doação e fomos solicitados a notificá-lo',
            'NotifyEmailTemp' => '<div>Prezado(a) {first_name},</div>

<div>
<p>Em nome dos padres e irm&atilde;os da Congrega&ccedil;&atilde;o do Verbo Divino, e do Povo de Deus que eles servem,<o:p></o:p> com muita alegria quero lhe informar que hemos recebido uma doa&ccedil;&atilde;o para os nossos trabalhos referente a:<o:p></o:p></p>
</div>

<div>-----------------------</div>

<div>
<div><strong>Doador: </strong>{first_name} {last_name}</div>

<div><strong>Doa&ccedil;&atilde;o para: </strong>{name_of_form}</div>

<div><strong>Inten&ccedil;&atilde;o:&nbsp;​</strong>​​{intention}</div>

<div><strong>Idioma: </strong>{card_lang}&nbsp;</div>

<div><strong>Cor da pasta: </strong>{folder_color}</div>

<div><strong>Imagem: </strong>{folder_image}</div>

<div><strong>Por vivos our falecidos:&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Solicitado por:&nbsp;</strong>{requested_by}</div>

<div><strong>Notifica&ccedil;&atilde;o para​​​​:</strong> {notify_first_name}&nbsp;{notify_last_name}</div>

<div><strong>Remessa internacional de certificado:</strong> {international_shipping}</div>

<div><strong>E-Card Link:</strong>&nbsp;{pe_e_card}</div>
</div>

<div>------------------------</div>

<div>
<div class="MsoNormal"><span lang="PT" style="mso-ansi-language:PT">Movido pelo mesmo esp&iacute;rito que inspirou S&atilde;o Arnaldo Janssen a fundar os Mission&aacute;rios do Verbo Divino, procuramos complementar seus esfor&ccedil;os pela difus&atilde;o da Palavra de Deus, por colaborar na forma&ccedil;&atilde;o de l&iacute;deres e no estabelecimento de vibrantes comunidades crist&atilde;s. Somos uma congrega&ccedil;&atilde;o mission&aacute;ria religiosa de mais de 6.000 sacerdotes e irm&atilde;os que trabalham em quase 80 pa&iacute;ses.<o:p></o:p></span><b style="mso-bidi-font-weight:normal"><span lang="PT" style="mso-ansi-language:PT"><o:p> </o:p></span></b></div>

<div class="MsoNormal"><b style="mso-bidi-font-weight:normal"><span lang="PT" style="mso-ansi-language:PT">Lembre-se de n&oacute;s em suas ora&ccedil;&otilde;es!<o:p></o:p></span></b><span lang="PT" style="mso-ansi-language:PT"><span style="mso-tab-count:2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><o:p></o:p></span></div>

<div>&nbsp;</div>

<div>No amor do Verbo Divino,<o:p></o:p></div>
</div>

<div><em>Pe. Janusz (Jo&atilde;o) Horowski, SVD</em></div>
',
        ],
        'sp' => [
            'AdminEmail' => 'divinewordgifts@uscsvd.org',
            'FromEmail' => 'divinewordgifts@uscsvd.org',
            'FromName' => 'Misioneros del Verbo Divino',
            'UserEmailSub' => 'Muchas Gracias Por Tu Donativo',
            'UserEmailTemplate' => '<div>Estimado(a) {first_name},</div>

<div>
<p>En nombre de los Misioneros del Verbo Divino y aquellos fieles a los que servimos, le damos las gracias por su donativo de <strong>{amount}</strong>. Su n&uacute;mero de confirmaci&oacute;n es <o:p></o:p><strong>{gift_id}</strong> y los detalles abajo:</p>
</div>

<div>-----------------------</div>

<div><strong>Donante: </strong>{first_name} {last_name}</div>

<div><strong>Donaci&oacute;n:</strong><strong> </strong>{name_of_form}</div>

<div><strong>Intenci&oacute;n: </strong>{intention}</div>

<div><strong>Idioma de la tarjeta&nbsp;</strong>{card_lang}&nbsp;</div>

<div><strong>Color de carpeta: </strong>{folder_color}</div>

<div><strong>Imagen: </strong>{folder_image}</div>

<div><strong>Por vivos o fallecidos&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Solicitado por:&nbsp;</strong>{requested_by}</div>

<div><strong>Notificar a:</strong> {notify_first_name}&nbsp;{notify_last_name}</div>

<div><strong>Env&iacute;o internacional​​ del certificado: </strong>{international_shipping}</div>

<div><strong>Enlace de tarjeta electr&oacute;nica:&nbsp;​​</strong>​​​​​{pe_e_card}</div>

<div>------------------------</div>

<div>
<div class="MsoNoSpacing"><span lang="ES-MX" style="mso-ansi-language:ES-MX">Su donativo ser&aacute; designado de acuerdo a su deseo y petici&oacute;n.<span style="mso-spacerun:yes">&nbsp; </span>En caso de no haber especificado un designio misionero o motivo de su donaci&oacute;n, nosotros nos aseguraremos de hacerla llegar especialmente a<o:p></o:p></span></div>

<div class="MsoNoSpacing"><span lang="ES-MX" style="mso-ansi-language:ES-MX">&bull; pobres marginados a quienes servimos<o:p></o:p></span></div>

<div class="MsoNoSpacing"><span lang="ES-MX" style="mso-ansi-language:ES-MX">&bull; seminaristas cuya educaci&oacute;n fundamos<o:p></o:p></span></div>

<div class="MsoNoSpacing"><span lang="ES-MX" style="mso-ansi-language:ES-MX">&bull; misioneros jubilados quienes han dedicado sus vidas esparciendo la Buena Nueva y el amor de Dios<o:p></o:p></span></div>

<div class="MsoNoSpacing"><span lang="ES-MX" style="mso-ansi-language:ES-MX"><o:p>&nbsp;</o:p></span></div>

<div class="MsoNoSpacing"><span lang="ES-MX" style="mso-ansi-language:ES-MX">Gracias por su donaci&oacute;n que recibimos electr&oacute;nicamente. Al as&iacute; enviarlo, ha contribuido a preservar la integridad de la creaci&oacute;n, a disminuir los costos de proceso; y los ahorros ser&aacute;n a&uacute;n m&aacute;s para distribuirlos con aquellos que lo necesitan.<span style="mso-spacerun:yes">&nbsp; </span>Si no lo ha intentado, le invitamos a visitar nuestra p&aacute;gina electr&oacute;nica e indagar sobre tal posibilidad www.divinewordgifts.org<o:p></o:p></span></div>

<div class="MsoNoSpacing"><span lang="ES-MX" style="mso-ansi-language:ES-MX">Puede dirigir sus preguntas llamando al 1-847-205-2300 o entre a verbodivino@uscsvd.org<o:p></o:p></span></div>

<div class="MsoNoSpacing"><span lang="ES-MX" style="mso-ansi-language:ES-MX"><span style="mso-spacerun:yes">&nbsp;</span><o:p></o:p></span></div>

<div class="MsoNoSpacing"><strong><span lang="ES-MX" style="mso-ansi-language:ES-MX">&iexcl;Que Dios bendiga su generosidad!</span></strong><span lang="ES-MX" style="mso-ansi-language:ES-MX"><o:p></o:p></span></div>

<div class="MsoNoSpacing"><span lang="ES-MX" style="mso-ansi-language:ES-MX"><o:p>&nbsp;</o:p></span></div>

<div class="MsoNoSpacing"><span lang="ES-MX" style="mso-ansi-language:ES-MX">Con una bendici&oacute;n sacerdotal, en el amor del Verbo Divino,<o:p></o:p></span></div>
</div>

<div><img alt="spansign.jpg" src="http://divinewordgifts.informaticsinc.com/download_file/view_inline/86" style="width: 70px; height: 55px;" /></div>

<div>
<div class="MsoNoSpacing"><em><span lang="ES-MX" style="mso-ansi-language:ES-MX">P. Janusz (Juan) Horowski, SVD</span></em><span lang="ES-MX" style="mso-ansi-language:ES-MX"><o:p></o:p></span></div>
</div>
',
            'AdminEmailSub' => 'Receipt Spanish - New Donation Has Been Added',
            'AdminEmailTemp' => '<p>We have received online donation with the following information:&nbsp;</p>

<div>-------------------------</div>

<div><strong>Requester: </strong>{first_name} {last_name}</div>

<div><strong>Donation for: </strong>{name_of_form}</div>

<div><strong>Intention: </strong>{intention}</div>

<div><strong>Card Language: </strong>{card_lang}&nbsp;</div>

<div><strong>Folder Color: </strong>{folder_color}</div>

<div><strong>Folder Image: </strong>{folder_image}</div>

<div><strong>Living or Deceased:&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Requested By:&nbsp;</strong>{requested_by}</div>

<div><strong>Notification send to:</strong> {notify_first_name}&nbsp;{notify_last_name}</div>

<div><strong>Certificate International Shipping:</strong> {international_shipping}</div>

<div><strong>E-Card Link:</strong>&nbsp;{pe_e_card}</div>

<div>-------------------------</div>
',
            'NotifyEmailSub' => 'Recibimos una donación y se nos pidió que le avisáramos',
            'NotifyEmailTemp' => '<div>Estimado(a) {first_name},</div>

<div>
<div>En nombre de los sacerdotes y hermanos de la Congregaci&oacute;n del Verbo Divino, y del Pueblo de Dios que ellos sirven, con alegr&iacute;a quiero informarle que hemos recibido una donaci&oacute;n referente a:<o:p></o:p></div>
</div>

<div>-----------------------</div>

<div>
<div><strong>Donante: </strong>{first_name} {last_name}</div>

<div><strong>Donaci&oacute;n:</strong><strong> </strong>{name_of_form}</div>

<div><strong>Intenci&oacute;n: </strong>{intention}</div>

<div><strong>Idioma de la tarjeta&nbsp;</strong>{card_lang}&nbsp;</div>

<div><strong>Color de carpeta: </strong>{folder_color}</div>

<div><strong>Imagen: </strong>{folder_image}</div>

<div><strong>Por vivos o fallecidos&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Solicitado por:&nbsp;</strong>{requested_by}</div>

<div><strong>Notificar a:</strong> {notify_first_name}&nbsp;{notify_last_name}</div>

<div><strong>Env&iacute;o internacional​​ del certificado: </strong>{international_shipping}</div>

<div><strong>Enlace de tarjeta electr&oacute;nica:&nbsp;​​</strong>​​​​​{pe_e_card}</div>
</div>

<div>------------------------</div>

<div>
<div class="MsoNormal"><span lang="ES" style="mso-ansi-language:
ES">Movidos por el mismo esp&iacute;ritu que inspir&oacute; a san Arnoldo Janssen a fundar los Misioneros del Verbo Divino, buscamos complementar sus esfuerzos por la difusi&oacute;n de la Palabra de Dios, y por colaborar en la formaci&oacute;n de l&iacute;deres y el establecimiento de vibrantes comunidades cristianos. Somos una congregaci&oacute;n religiosa misionera de m&aacute;s de 6 mil sacerdotes y hermanos trabajando en casi 80 pa&iacute;ses.<o:p></o:p></span><b style="mso-bidi-font-weight:normal"><span lang="ES" style="mso-ansi-language:ES"><o:p> </o:p></span></b></div>

<div class="MsoNormal"><b style="mso-bidi-font-weight:normal"><span lang="ES" style="mso-ansi-language:ES">&iexcl;Acu&eacute;rdate de nosotros en tus oraciones!<o:p></o:p></span></b></div>

<div>&nbsp;</div>

<div>En el amor del Verbo Divino,<o:p></o:p></div>
</div>

<div><em><span lang="ES-MX" style="mso-ansi-language:ES-MX">P. Janusz (Juan) Horowski, SVD</span></em></div>
',
        ],
        'vi' => [
            'AdminEmail' => 'Unghotruyengiao@dwci.edu',
            'FromEmail' => 'Unghotruyengiao@dwci.edu',
            'FromName' => 'Society of the Divine Word',
            'UserEmailSub' => 'Thank You For Your Donation',
            'UserEmailTemplate' => '<div>Dear&nbsp;{first_name},</div>

<div>On behalf of the missionaries of the Society of the Divine Word and the people of faith they serve, I thank you for your gift of&nbsp;<strong>{amount}</strong>.</div>

<div>Your confirmation number is <strong>{gift_id}</strong> and the details of your request follow:</div>

<div>-----------------------</div>

<div><strong>Requester: </strong>{first_name} {last_name}</div>

<div><strong>Donation for: </strong>{name_of_form}</div>

<div><strong>Intention: </strong>{intention}</div>

<div><strong>Card Language: </strong>{card_lang}&nbsp;</div>

<div><strong>Folder Color: </strong>{folder_color}</div>

<div><strong>Folder Image: </strong>{folder_image}</div>

<div><strong>Living or Deceased:&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Requested By:&nbsp;</strong>{requested_by}</div>

<div><strong>Notification send to:</strong> {notify_first_name}&nbsp;{notify_last_name}</div>

<div><strong>International Shipping:</strong> {international_shipping}</div>

<div><strong>E-Card Link:</strong>&nbsp;{pe_e_card}</div>

<div>------------------------</div>

<div>This gift will be directed as you requested. if you did not specify a particular mission or purpose, we will share your gift with many people, especially:</div>

<ul>
	<li>
	<div>the poor and marginalized whom we serve</div>
	</li>
	<li>
	<div>seminarians whose educations we fund</div>
	</li>
	<li>
	<div>retired missionaries who have devoted their lives to spreading the Good News of God&#39;s love for all.</div>
	</li>
</ul>

<div>Thank you for making your donation electronically. By doing so, you have helped to preserve the integrity of God&#39;s creation and also have helped us lower our costs so that we can send more funds to those in need. If you haven&#39;t already done so, we invite you to bookmark our website: www.divinewordgifts.org.</div>

<div>If you have questions, you can reach us at (800)-775-0030 or development@uscsvd.org</div>

<div>May God reward you for your generosity.</div>

<div>With my priestly blessing, in the Divine Word,</div>

<div><em>Fr. Linh</em></div>
',
            'AdminEmailSub' => 'New Donation Has Been Added',
            'AdminEmailTemp' => '<p>We have recieved online donation with the following information:&nbsp;</p>

<div>-------------------------</div>

<div><strong>Requester: </strong>{first_name} {last_name}</div>

<div><strong>Donation for: </strong>{name_of_form}</div>

<div><strong>Intention: </strong>{intention}</div>

<div><strong>Card Language: </strong>{card_lang}&nbsp;</div>

<div><strong>Folder Color: </strong>{folder_color}</div>

<div><strong>Folder Image: </strong>{folder_image}</div>

<div><strong>Living or Deceased:&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Requested By:&nbsp;</strong>{requested_by}</div>

<div><strong>Notification send to:</strong> {notify_first_name}&nbsp;{notify_last_name}</div>

<div><strong>International Shipping:</strong> {international_shipping}</div>

<div><strong>E-Card Link:</strong>&nbsp;{pe_e_card}</div>

<div>-------------------------</div>
',
            'NotifyEmailSub' => 'We received donation and we were asked to notify you',
            'NotifyEmailTemp' => '<div>Dear&nbsp;{first_name},</div>

<div>On behalf of the priests and brothers of the Society of the Divine Word, and people of faith to whom they minister, I am happy to inform you that we have received a donation for:</div>

<div>-----------------------</div>

<div><strong>Requester: </strong>{first_name} {last_name}</div>

<div><strong>Donation for: </strong>{name_of_form}</div>

<div><strong>Intention: </strong>{intention}</div>

<div><strong>Card Language: </strong>{card_lang}&nbsp;</div>

<div><strong>Folder Color: </strong>{folder_color}</div>

<div><strong>Folder Image: </strong>{folder_image}</div>

<div><strong>Living or Deceased:&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Requested By:&nbsp;</strong>{requested_by}</div>

<div><strong>Notification send to:</strong> {notify_first_name}&nbsp;{notify_last_name}</div>

<div><strong>International Shipping:</strong> {international_shipping}</div>

<div><strong>E-Card Link:</strong>&nbsp;{pe_e_card}</div>

<div>&nbsp;</div>

<div>------------------------</div>

<div>Moved by the same spirit that inspired St. Arnold Janssen to found the Divine Word Missionaries, we seek to complement his efforts of spreading the Word of God, collaborating in the formation of leaders, and establishing vibrant Christian communities. We are a religious missionary congregation of more than 6,000 priests and brothers working in almost 80 countries.<b>&nbsp;</b></div>

<div><b>Remember us in your prayers!</b></div>

<div>With my priestly blessing, in the Divine Word,</div>

<div><i>Fr. Linh</i></div>
',
        ],
    ],
];
