<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-04-08T10:07:42-05:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      donorPerfectLogin
 * @group     integration
 * @namespace mass_enrollment
 * -----------------------------------------------------------------------------
 */
return [
    'safeUsername' => 'SDW2019',
    'safePassword' => 'iksworoh682j',
    'donorPerfectUsername' => 'divineword',
    'donorPerfectPassword' => 'DWb4cikLKkOA',
    'donorPerfectLogin' => 1,
];
