<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-10-08T12:27:02+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      Korean
 * @group     langkeys
 * @namespace mass_enrollment
 * -----------------------------------------------------------------------------
 */
return [
    'English' => 'English',
    'Polish' => 'Polish',
    'Spanish' => 'Spanish',
    'Portuguese' => 'Portuguese',
    'French' => 'French',
    'German' => 'German',
    'Croatian' => 'Croatian',
    'Hungarian' => 'Hungarian',
    'Italian' => 'Italian',
    'Lithuanian' => 'Lithuanian',
    'Slovak' => 'Slovak',
    'Vietnamese' => 'Vietnamese',
    'Cebuano' => 'Cebuano',
    'Tagalog' => 'Tagalog',
    'Iloko' => 'Iloko',
    'Korean' => 'Korean',
];
