<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-10-08T12:39:48+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      English
 * @group     po
 * @namespace mass_enrollment
 * -----------------------------------------------------------------------------
 */
return [
    'English' => 'Angrezis',
];
