<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-05-14T09:08:25-05:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      DoubleClickMessage
 * @group     pt
 * @namespace mass_enrollment
 * -----------------------------------------------------------------------------
 */
return [
    'ContactDetailsTab' => 'Detalhes de Contacto',
    'card-black-madonna' => 'Nossa Senhora de Czestochowa',
    'card-christmas' => 'Natal
',
    'card-divine-mercy' => 'Divina Misericórdia
',
    'card-eucharist' => 'Eucaristia
',
    'card-good-shepherd' => 'Bom Pastor
',
    'card-guardian-angel' => 'Anjo da Guarda
',
    'card-heart-jesus' => 'Sagrado Coração de Jesus
',
    'card-heart-jesus-two' => 'Sagrado Coração de Jesus (2)
',
    'DonationDetailsTab' => 'Detalhes da Doação',
    'OcassionLabel' => 'Seleccione a Ocasião
',
    'FolderDetailsLabel' => 'Detalhes da pasta/certificado',
    'SelectImageLabel' => 'Seleccione a imagem
',
    'SelectFolderColorLabel' => 'Seleccione cor da pasta',
    'LanguageLabel' => 'Seleccione o idioma',
    'LanguageSelectLabel' => 'Seleccione o idioma',
    'RequestedByLabel' => 'Requerido por',
    'OccasionRequiredError' => 'O campo "Ocasião" é obrigatório.',
    'EnrollmentDetailsTitle' => 'Detalhes da inscrição',
    'Gold' => 'Dourado',
    'Blue' => 'Azul',
    'Red' => 'Vermelho',
    'Silver' => 'Prata',
    'White' => 'Branco',
    'English' => 'Inglês',
    'Polish' => 'Polonês',
    'Spanish' => 'Espanhol',
    'Portuguese' => 'Português',
    'French' => 'Francês',
    'German' => 'Alemão',
    'Croatian' => 'Croata',
    'Hungarian' => 'Húngaro',
    'Italian' => 'Italiano',
    'Lithuanian' => 'Lituânia',
    'Slovak' => 'Eslovaco',
    'Vietnamese' => 'Vietnamita',
    'Cebuano' => 'Cebuano',
    'Tagalog' => 'Tagalog',
    'Iloko' => 'Ilocano',
    'Korean' => 'Coreano',
    'FirstNameRequrired' => 'O campo "Primeiro nome" é obrigatório.',
    'LastNameRequrired' => 'O campo "Sobrenome" é obrigatório.',
    'AddressRequired' => 'O campo "Endereço" é obrigatório.',
    'EmailAddressRequrired' => 'O campo "Endereço de email" é obrigatório.',
    'CityRequired' => 'O campo "Cidade" é obrigatório',
    'CountryRequired' => 'O campo "País" é obrigatório.',
    'ZipRequired' => 'O campo "Código Postal" é obrigatório',
    'StateRequired' => 'O campo "Estado" é obrigatório',
    'CardHolderNameRequired' => 'O campo "Nome do titular do cartão" é obrigatório.',
    'CardTypeRequired' => 'O campo "Tipo de cartão" é obrigatório.',
    'CardNumberRequired' => 'O campo "Número do cartão" é obrigatório.',
    'ExpiryMonthRequired' => 'O campo "Mês de vencimento" é obrigatório.
',
    'ExpiryYearRequired' => 'O campo "Ano de vencimento" é obrigatório.',
    'CVVRequired' => 'O campo "CVV" é obrigatório.',
    'NotificationLanguageRequired' => 'O campo "Idioma da notificação" é obrigatório.',
    'RequestedByRequired' => 'O campo "Solicitado por" é obrigatório.',
    'IndividualNameRequired' => 'O campo "Nome do indivíduo" é obrigatório.',
    'FamilyNameRequired' => 'O campo "Nome da família" é obrigatório.',
    'NmassRequiredError' => 'O campo "Número de missas" é obrigatório.',
    'IntentionRequiredError' => 'O campo "Sua(s) Intenção(ões)" é obrigatório.',
    'WhoReqRequiredError' => 'O campo "Quem está solicitando missas" é obrigatório.',
    'DonationRequired' => 'O campo "Valor da doação" é obrigatório.',
    'LivDecRequiredError' => 'O campo "Vivo/Falecido" é obrigatório.',
    'MessageSuccess' => 'Obrigado pelo pedido.',
    'InvalidCaptcha' => 'Código Captcha inválido.',
    'SupportWithDonationRequired' => 'O campo “O que gostaria de apoiar com esta doação das Missas?” é obrigatório.',
    'ActualSize' => 'O tamanho real da pasta aberta é 13 x 8,5 polegadas',
    'ContactFormSaved' => 'Os detalhes do contacto foram salvos com sucesso. Continue adicionando os detalhes do pagamento abaixo.',
    'EnrollFormSaved' => 'Os detalhes da doação foram salvos com sucesso. Continue adicionando os detalhes do contacto abaixo.',
    'EnrollmentTypeTitle' => 'Tipo de inscrição',
    'EnrollmentDateLabel' => 'Data da inscrição',
    'FamilyPriceLabel' => 'De família',
    'IndividualPriceLabel' => 'Individual',
    'IndividualTextTitle' => 'Por favor, escreva o nome do indivíduo que quer inscrever',
    'IndividualEnrollNamePlaceholder' => 'Nome do indivíduo',
    'OutOFLabel' => 'fora de',
    'CharacterLabel' => 'caracteres permitidos',
    'FamilyEnrollNameTitle' => 'Por favor inscreva o nome completo da família, e.g. a Família Carvalho, ou inscreva o nome de cada membro de família separado por vírgulas',
    'FamiliyEnrollNamePlaceholder' => 'Nome da família',
    'RequestedByInfo' => 'Digite a sua mensagem e assine seu nome, por exemplo, "Com amor, João e Maria"',
    'RequestedByTitle' => 'Inscreva  o seu nome e a sua mensagem como ela deverá constar no certificado',
    'SpecialInstructionsLabel' => 'Instruções especiais não serão incluídas nas notificações',
    'SpecialInstructionsTitle' => 'Instruções especiais - opcional',
    'LivingLabel' => 'Escolha se for para vivo
',
    'DeceasedLabel' => 'Escolha se for para morto',
    'SendNotificationLabel' => 'Envie notificação (ou cartão, se for seleccionado) para a outra pessoa por mim.',
    'NotificationLanguangeLabel' => 'Idioma de notificação',
    'NumberOfMassesInfo' => 'O número 9 indicará a Novena de Missas',
    'RequestDetailsLabel' => 'Detalhes do pedido',
    'KEYCOLLEGE' => 'Formação de novos missionários 
',
    'KEYMISSION' => 'Projectos Missionários
',
    'KEYRETIREMENT' => 'Cuidado dos missionários aposentados
',
    'KEYMOSTNEEDED' => 'Onde for mais necessário 
',
    'PaymentFailed' => 'Pagamento falhou. Por favor, tente novamente mais tarde.',
    'ConfirmCancel' => 'Tem certeza de que deseja cancelar isso? Essa ação não pode ser desfeita.',
    'TotalPayment' => 'Total geral',
    'SelectYourImage' => 'Seleccione a imagem',
    'AcceptAndClose' => 'Aceitar e fechar',
    'CardOptions' => 'Opções do cartão',
    'CardImage' => 'Imagem',
    'FolderColor' => 'Cor da pasta',
    'Baptism' => 'Baptismo',
    'Confirmation' => 'Confirmação',
    'Graduation' => 'Graduação',
    'Birthday' => 'Aniversário',
    'TitleLabel' => 'Título
',
    'FirstNameLabel' => 'Nome
',
    'LastNameLabel' => 'Sobrenome
',
    'AddressLabel' => 'Endereço
',
    'Address2Label' => 'Endereço 2
',
    'CityLabel' => 'Cidade
',
    'CountryLabel' => 'País
',
    'StateProvinceLabel' => 'Estado/Província
',
    'ZipPostalLabel' => 'Código Postal
',
    'ZipPostalPlaceholder' => 'Código Postal
',
    'EmailLabel' => 'Email
',
    'SupportWithDonationLabel' => 'O que gostaria de apoiar com esta doação das Missas?',
    'CountinueLabel' => 'Continuar',
    'MassDetailsLabel' => 'Detalhes da Missa',
    'NumberOfMassesLabel' => 'Número de Missas
',
    'YourIntentionsLabel' => 'Sua(s) Intenção(ões)',
    'YourIntentionsPlaceholder' => 'Por favor, liste as suas intenções',
    'RequestingMassesLabel' => 'Quem está a solicitar as missas',
    'RequestingMassesPlaceholder' => 'Por favor, escreva o nome completo da pessoa que solicita as missas',
    'DonationAmountLabel' => 'Valor da doação',
    'AddressDetailsLabel' => 'Endereço',
    'CorrectFollowing' => 'Corrija os seguintes erros antes de continuar:',
    'DonationAmountPlaceholder' => 'Montante (Somente valor numérico permitido)',
    'DeliveryDetailsLabel' => 'Detalhes da entrega',
    'NameLabel' => 'Nome',
    'HomePhoneLabel' => 'Telefone de contacto',
    'CellPhoneLabel' => 'Celular',
    'BackLabel' => 'Voltar',
    'CancelLabel' => 'Cancelar',
    'ContinueLabel' => 'Continuar',
    'PaymentDetailsTab' => 'Detalhes de Pagamento',
    'OrderSummaryLabel' => 'Resumo da sua Ordem',
    'NameOfIndividualFamilyLabel' => 'Nome do indivíduo/família',
    'InternationalShippingLabel' => 'Envio internacional',
    'PaymentInformationLabel' => 'Informação de pagamento',
    'CardHolderNameLabel' => 'Nome do Titular',
    'CardTypeLabel' => 'Tipo de cartão',
    'CardNumberLabel' => 'Número do cartão',
    'ExpMonthLabel' => 'Mês de vencimento',
    'ExpYearLabel' => 'Ano de vencimento',
    'ExpMonthPlaceholder' => 'Mês',
    'ExpYearPlaceholder' => 'Ano',
    'CVVLabel' => 'CVV',
    'SupportWithDonationInfo' => 'Solicitar Missas, Inscrição Perpétua, etc., você apóia nosso ministério missionário.',
    'CVVPlaceholder' => 'Código de segurança
',
    'BillingDetailsLabel' => 'Detalhes de cobrança',
    'SameAsContactDetail' => 'Os mesmos que nos detalhes de contacto
',
    'SubmitLabel' => 'Enviar',
    'EmailAddressInvalid' => 'Endereço de email inválido. Verifique se o seu email não possui caracteres nacionais.',
    'card-anthony' => 'Santo António
',
    'card-fatima-one' => 'Nossa Senhora de Fátima
',
    'card-guadalupe' => 'Nossa Senhora de Guadalupe
',
    'card-holy-family' => 'Sagrada Família
',
    'card-immaculate-mary-one' => 'Maria Imaculada (1)',
    'card-immaculate-mary-two' => 'Maria Imaculada (2)',
    'card-jesus-children' => 'Jesus com Crianças
',
    'card-jesus-christ' => 'Jesus Cristo
',
    'card-jesus-garden-one' => 'Jesus no Jardim das Oliveiras 1
',
    'card-jesus-garden-two' => 'Jesus no Jardim das Oliveiras
',
    'card-john-paul-one' => 'João Paulo II
',
    'card-john-paul-two' => 'João Paulo II (2)
',
    'FlipCard' => 'Vire o cartão ',
    'card-immaculate-heart' => 'Imaculado Coração de Maria
',
    'card-joseph' => 'São José
',
    'card-lady-angels' => 'Nossa Senhora dos Anjos
',
    'card-lady-fatima-two' => 'Nossa Senhora de Fátima (2)
',
    'card-lady-street' => 'Nossa Senhora dos Peregrinos
',
    'card-mother-help' => 'Nossa Senhora do Perpétuo Socorro
',
    'card-pentecost' => 'Pentecostes
',
    'card-pieta' => 'Pietá - Maria com Jesus nos Braços
',
    'card-pio' => 'Padre Pio de Pietrelcina
',
    'card-resurraction-one' => 'Ressurreição (1)
',
    'card-resurrection-two' => 'Ressurreição (2)
',
    'card-sunrise' => 'Nascer do Sol
',
    'card-sunset' => 'Pôr do Sol
',
    'NumberOfMassesPlaceholder' => 'Número de Missas (somente valor numérico permitido)',
    'DonateNow' => 'Faça doação',
    'SearchThisSite' => 'Procure este site',
    'NumberOfMassesLabelSecondary' => 'A oferta para uma Santa Missa é de US $ 10,00',
    'PrintReceipt' => 'Imprimir recibo',
    'ThankYouforthePayment' => 'Obrigado pela doação',
    'Areyousureyouwanttosubmittheorder' => 'Tem certeza de que deseja enviar o pedido?',
    'Cardnumbermustcontainonlydigits' => 'O número do cartão deve conter apenas dígitos.',
    'TheStateProvincefieldisrequired' => 'O campo "Estado/Província" é obrigatório',
    'AtleastoneStateProvinceshouldbeselected' => 'Pelo menos um "Estado/Província" deve ser selecionado',
    'Cardhasexpired' => 'O cartão venceu',
    'MatchDonorReceiverEmailID' => 'O email do doador e do destinatário deve ser diferente.',
    'AckFormNoteForCardOption' => 'O tamanho do cartão aberto é 21,5 x 17,7 cm.',
    'GregorianDonation' => 'A doação por 30 Missas Gregorianas é de $400.00',
    'Form1' => 'Liga Missionária das Missas Perpétuas',
    'Form2' => 'Liga Missionária das Missas Perpétuas',
    'Form3' => 'Liga Missionária das Missas Perpétuas',
    'Form4' => 'Liga Missionária das Missas Perpétuas',
    'Form5' => 'Santas Missas',
    'Form6' => 'Missas Gregorianas',
    'Form7' => 'Missas pelos falecidos',
    'Form8' => 'Novena das Missas pelo dia das Mães',
    'Form9' => 'Missas pelos estudantes',
    'Form10' => 'Missas pela cura dos enfermos',
    'Form13' => 'Missas de primeira sexta-feira de mês',
    'Month' => 'Mês',
    'Jan' => 'jan',
    'Feb' => 'fev',
    'Mar' => 'mar',
    'Apr' => 'abr',
    'May' => 'maio',
    'Jun' => 'jun',
    'Jul' => 'jul',
    'Aug' => 'ago',
    'Sep' => 'set',
    'Oct' => 'out',
    'Nov' => 'nov',
    'Dec' => 'dez',
    'DeceasedPerson' => 'Por favor, escreva o nome completo da pessoa falecida.',
    'InternationalCharge' => '$10.00 serão adicionados automaticamente a pedidos enviados fora dos Estados Unidos',
    'livinglabel' => 'Vivos',
    'deceasedlabel' => 'Falecidos',
    'ViewPreview' => 'Visualizar Certificado',
    'Address3Label' => 'Endereço 3',
    'CheckIfYouWantTheCardOnBehalf' => 'Marque, se deseja enviar o cartão em seu nome.',
    'notApplicable' => 'N/D',
    'LivingOrDeceased' => 'Vivos ou falecidos',
    'SelectOccasion' => 'Seleccione a ocasião',
    'ExpressionofCondolences' => 'Expressão de condolências',
    'FirstCommunion' => 'Primeira Comunhão',
    'WeddingAnniversary' => 'Aniversário',
    'OtherOccasion' => 'Outra ocasião',
    'or' => '- OU -',
    'SupportWithDonationPlaceholder' => 'Selecione aqui, o que gostaria de apoiar com esta doação das Missas',
    'ContactDetailsHeader' => 'Contacto',
    'No' => 'Não',
    'Yes' => 'Sim',
    'Form11' => 'Novena da Misericórdia Divina',
    'Form12' => 'Novena do Dia dos Pais',
    'ExpressionOfCondolences' => 'Expressão de condolências',
    'paymentButtonText' => 'PAGAR',
    'paymentInstructionText' => 'Adicione o número do cartão, data de vencimento (mês/ano) e código de segurança.',
    'DoubleClickMessage' => 'Depois de fazer o clique no ENVIAR e adicionar a sua informação do cartão de crédito, clique em PAGAR e aguarde pelo seu recibo. Não clique no PAGAR uma segunda vez.',
];
