<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-03-22T10:00:22-05:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      pl.Template
 * @group     receipts
 * @namespace mass_enrollment
 * -----------------------------------------------------------------------------
 */
return [
    'Default' => [
        'Template' => '<div class="row">
<div class="col-sm-6 text-left">
<h4>Billed To</h4>

<p>{first_name} {last_name}<br />
{billing_address}<br />
{email}</p>

<p>&nbsp;</p>
</div>
</div>

<p>Thank you for the donation of <strong>{amount}</strong></p>

<p>&nbsp;</p>

<p>Form Submission Details:</p>

<p>-----------------------</p>

<div><strong>Name: </strong>{first_name} {last_name}</div>

<div><strong>Name of the Form: </strong>{name_of_form}</div>

<div><strong>Intention: </strong>{intention}</div>

<div><strong>Card Language: </strong>{card_lang}&nbsp;</div>

<div><strong>Folder Color: </strong>{folder_color}</div>

<div><strong>Folder Image: </strong>{folder_image}</div>

<div><strong>Living or Deceased:&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Requested By:&nbsp;</strong>{requested_by}</div>

<div><strong>Notify Name:</strong> {notify_first_name}&nbsp;{notify_last_name}&nbsp;</div>

<div><strong>International Shipping:</strong> {international_shipping}</div>

<div><strong>PE E-Card Link:</strong>&nbsp;{pe_e_card}</div>

<div><strong>Transaction ID:</strong>&nbsp;{transaction_id}</div>

<p>------------------------</p>

<p>Thank you for making your donation electronically. By doing so, you have helped to preserve the integrity of God&#39;s creation and also have helped us lower our costs so that we can send more funds to those in need. If you haven&#39;t already done so, we invite you to bookmark our website: www.divinewordgifts.org.</p>

<p>If you have questions, you can reach us at (800)-775-0030 or development@uscsvd.org</p>

<p>May God reward you for your generosity.</p>
',
    ],
    'en' => [
        'Template' => '<div class="row">
<div class="col-sm-6 text-left">
<h4>Billed To</h4>

<p>{first_name} {last_name}<br />
{billing_address}<br />
{email}</p>

<p>&nbsp;</p>
</div>
</div>

<p>Thank you for the donation of <strong>{amount}</strong></p>

<p>&nbsp;</p>

<p>Form Submission Details:</p>

<p>-----------------------</p>

<div><strong>Name: </strong>{first_name} {last_name}</div>

<div><strong>Name of the Form: </strong>{name_of_form}</div>

<div><strong>Intention: </strong>{intention}</div>

<div><strong>Card Language: </strong>{card_lang}&nbsp;</div>

<div><strong>Folder Color: </strong>{folder_color}</div>

<div><strong>Folder Image: </strong>{folder_image}</div>

<div><strong>Living or Deceased:&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Requested By:&nbsp;</strong>{requested_by}</div>

<div><strong>Notify Name:</strong> {notify_first_name}&nbsp;{notify_last_name}&nbsp;</div>

<div><strong>International Shipping:</strong> {international_shipping}</div>

<div><strong>PE E-Card Link:</strong>&nbsp;{pe_e_card}</div>

<div><strong>Transaction ID:</strong>&nbsp;{transaction_id}</div>

<p>------------------------</p>

<p>Thank you for making your donation electronically. By doing so, you have helped to preserve the integrity of God&#39;s creation and also have helped us lower our costs so that we can send more funds to those in need. If you haven&#39;t already done so, we invite you to bookmark our website: www.divinewordgifts.org.</p>

<p>If you have questions, you can reach us at (800)-775-0030 or development@uscsvd.org</p>

<p><strong>May God reward you for your generosity.</strong></p>
',
    ],
    'pl' => [
        'Template' => '<h4>Pobrano od:</h4>

<div>{first_name} {last_name}<br />
{billing_address}<br />
{email}</div>

<div>&nbsp;</div>

<div>Dziękujemy za ofiarę&nbsp;<strong>{amount}</strong></div>

<div>&nbsp;</div>

<div>Szczeg&oacute;ły zam&oacute;wienia:</div>

<div>&nbsp;</div>

<div>-----------------------</div>

<div>
<div><b>Ofiarodawca: </b>{first_name} {last_name}</div>

<div><b>Ofiara na: </b>{name_of_form}</div>

<div><b>Intencja(e): </b>{intention}</div>

<div><b>Język certyfikatu/karty: </b>{card_lang}&nbsp;</div>

<div><b>Kolor oprawy: </b>{folder_color}</div>

<div><b>Obrazek: </b>{folder_image}</div>

<div><b>Za żyjących czy zmarłych:&nbsp;</b>{living_or_deceased}</div>

<div><b>Wpisu dokonuje:&nbsp;</b>{requested_by}</div>

<div><b>Zawiadomienie otrzyma:</b> {notify_first_name}&nbsp;{notify_last_name}&nbsp;</div>

<div><b>Wysyłka międzynarodowa:</b> {international_shipping}</div>

<div><b>E-Card Link:</b>&nbsp;{pe_e_card}</div>

<div><b>Numer transakcji:</b>&nbsp;{transaction_id}</div>
</div>

<div>------------------------</div>

<div>&nbsp;</div>

<div>
<p>Dziękujemy za złożenie ofiary drogą elektroniczną. W ten spos&oacute;b pomogłeś zachować integralność Bożego stworzenia i obniżyć nasze koszty, abyśmy mogli wysłać więcej funduszy potrzebującym. Jeśli jeszcze tego nie zrobiłeś, zapraszamy do umieszczenia naszej strony internetowej: <a href="http://www.divinewordgifts.org">www.divinewordgifts.org</a> w zakładce &bdquo;ulubione&rdquo;<br />
Jeśli masz pytania, skontaktuj się z nami pod numerem (847) -753-7422 lub wyślij emaila na adres MisjonarzeWerbisci@uscsvd.org</p>

<p><strong>Niech dobry B&oacute;g wynagrodzi Twoją hojność.</strong></p>
</div>
',
    ],
    'pt' => [
        'Template' => '<h4>Recibido de:</h4>

<div>{first_name} {last_name}<br />
{billing_address}<br />
{email}</div>

<div>&nbsp;</div>

<div>Obrigado pela doa&ccedil;&atilde;o de&nbsp; <strong>{amount}</strong></div>

<div>&nbsp;</div>

<div>Detalhes do pedido:</div>

<div>&nbsp;</div>

<div>-----------------------</div>

<div>
<div><b>Doador: </b>{first_name} {last_name}</div>

<div><b>Doa&ccedil;&atilde;o para: </b>{name_of_form}</div>

<div><b>Inten&ccedil;&atilde;o:&nbsp;​</b>​​{intention}</div>

<div><b>Idioma do cart&atilde;o: </b>{card_lang}&nbsp;</div>

<div><b>Cor da pasta: </b>{folder_color}</div>

<div><b>Imagem: </b>{folder_image}</div>

<div><b>Por vivos our falecidos:&nbsp;</b>{living_or_deceased}</div>

<div><b>Solicitado por:&nbsp;</b>{requested_by}</div>

<div><b>Notifica&ccedil;&atilde;o para​​​​:</b> {notify_first_name}&nbsp;{notify_last_name}</div>

<div><b>Remessa internacional:</b> {international_shipping}</div>

<div><b>E-Card Link:</b>&nbsp;{pe_e_card}</div>

<div><b>Identificador de doa&ccedil;&atilde;o:</b>&nbsp;{transaction_id}</div>
</div>

<div>------------------------</div>

<div>&nbsp;</div>

<div>
<p>Obrigado por fazer sua doa&ccedil;&atilde;o eletronicamente. Ao fazer isso, voc&ecirc; ajudou a preservar a integridade da cria&ccedil;&atilde;o de Deus e tamb&eacute;m nos ajudou a reduzir nossos custos, para que possamos enviar mais fundos para os necessitados. Se voc&ecirc; ainda n&atilde;o o fez, convidamos voc&ecirc; a marcar nosso site www.divinewordgifts.org&nbsp;como favorito.</p>

<p>Em caso de d&uacute;vidas, entre em contato pelo telefone (800) -775-0030 ou verbodivino@uscsvd.org</p>

<p><strong>Que Deus o recompense por sua generosidade!</strong></p>
</div>
',
    ],
    'sp' => [
        'Template' => '<h4>Recibido de:</h4>

<div>{first_name} {last_name}<br />
{billing_address}<br />
{email}</div>

<div>&nbsp;</div>

<div>Gracias por la donaci&oacute;n de&nbsp;<strong>{amount}</strong></div>

<div>&nbsp;</div>

<div>Detalles del pedido:</div>

<div>-----------------------</div>

<div>
<div>&nbsp;</div>

<div><b>Donante: </b>{first_name} {last_name}</div>

<div><b>Donaci&oacute;n para: </b>{name_of_form}</div>

<div><b>Intenci&oacute;n: </b>{intention}</div>

<div><b>Idioma de la tarjeta&nbsp;</b>{card_lang}&nbsp;</div>

<div><b>Color de carpeta: </b>{folder_color}</div>

<div><b>Imagen: </b>{folder_image}</div>

<div><b>Por vivos o fallecidos&nbsp;</b>{living_or_deceased}</div>

<div><b>Solicitado por:&nbsp;</b>{requested_by}</div>

<div><b>Notificar a:</b> {notify_first_name}&nbsp;{notify_last_name}</div>

<div><b>Env&iacute;o internacional​​: </b>{international_shipping}</div>

<div><b>Enlace de tarjeta electr&oacute;nica:&nbsp;​​</b>​​​​​{pe_e_card}</div>

<div><b>Identificador de d</b><b>onaci&oacute;n</b><b>:</b>&nbsp;{transaction_id}</div>
</div>

<div>------------------------</div>

<div>&nbsp;</div>

<div>
<p>Gracias por hacer tu donaci&oacute;n electr&oacute;nicamente. Al hacerlo, has ayudado a preservar la integridad de la creaci&oacute;n de Dios y tambi&eacute;n nos has ayudado a reducir nuestros costos para que podamos enviar m&aacute;s fondos a los necesitados. Si a&uacute;n no lo has hecho, lo invitamos a marcar nuestro sitio web: www.divinewordgifts.org como favorito.<br />
Si tienes preguntas, puedes comunicarte con nosotros al (800) -775-0030 o verbodivino@uscsvd.org</p>

<p><strong>Que Dios te recompense por tu generosidad.</strong></p>
</div>
',
    ],
    'vi' => [
        'Template' => '<div>Billed To</div>

<div>{first_name} {last_name}<br />
{billing_address}<br />
{email}</div>

<div>&nbsp;</div>

<div>Thank you for the donation of <strong>{amount}</strong></div>

<div>&nbsp;</div>

<div>Form Submission Details:</div>

<div>-----------------------</div>

<div><strong>Name: </strong>{first_name} {last_name}</div>

<div><strong>Name of the Form: </strong>{name_of_form}</div>

<div><strong>Intention: </strong>{intention}</div>

<div><strong>Card Language: </strong>{card_lang}&nbsp;</div>

<div><strong>Folder Color: </strong>{folder_color}</div>

<div><strong>Folder Image: </strong>{folder_image}</div>

<div><strong>Living or Deceased:&nbsp;</strong>{living_or_deceased}</div>

<div><strong>Requested By:&nbsp;</strong>{requested_by}</div>

<div><strong>Notify Name:</strong> {notify_first_name}&nbsp;{notify_last_name}&nbsp;</div>

<div><strong>International Shipping:</strong> {international_shipping}</div>

<div><strong>E-Card Link:</strong>&nbsp;{pe_e_card}</div>

<div><strong>Transaction ID:</strong>&nbsp;{transaction_id}</div>

<div>------------------------</div>

<div>&nbsp;</div>

<div>Thank you for making your donation electronically. By doing so, you have helped to preserve the integrity of God&#39;s creation and also have helped us lower our costs so that we can send more funds to those in need. If you haven&#39;t already done so, we invite you to bookmark our website: www.divinewordgifts.org.</div>

<div>If you have questions, you can reach us at (800)-775-0030 or development@uscsvd.org</div>

<div>&nbsp;</div>

<div>May God reward you for your generosity.</div>
',
    ],
];
