<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-05-14T09:08:50-05:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      DoubleClickMessage
 * @group     sp
 * @namespace mass_enrollment
 * -----------------------------------------------------------------------------
 */
return [
    'ContactDetailsTab' => 'Mis Datos de Contacto',
    'EnrollmentDetailsTitle' => 'Detalles de Inscripción',
    'EnrollmentDateLabel' => 'Fecha de inscripción (opcional)',
    'DonationDetailsTab' => 'Detalles de la Donación',
    'OcassionLabel' => 'Ocasión',
    'FolderDetailsLabel' => 'Detalles de carpeta/tarjeta',
    'SelectImageLabel' => 'Seleccione la imagen',
    'SelectFolderColorLabel' => 'Seleccione el color de carpeta',
    'LanguageLabel' => 'Seleccione el idioma',
    'LanguageSelectLabel' => 'Seleccione el idioma',
    'RequestedByLabel' => 'Solicitado por',
    'OccasionRequiredError' => 'El campo "Ocasión" es obligatorio.',
    'EnrollmentTypeTitle' => 'Tipo de inscripción',
    'FamilyPriceLabel' => 'Familiar',
    'IndividualPriceLabel' => 'Individual',
    'IndividualTextTitle' => 'Indique el nombre del inscripto - individual',
    'IndividualEnrollNamePlaceholder' => 'Nombre del individuo',
    'OutOFLabel' => 'fuera de',
    'CharacterLabel' => 'caracteres permitidos',
    'FamilyEnrollNameTitle' => 'Enumere un apellido completo, p. ej. La Familia Gutierrez, o enumere el nombre de cada miembro de la familia separado por comas.',
    'FamiliyEnrollNamePlaceholder' => 'Nombre de la familia',
    'RequestedByInfo' => 'Escriba su mensaje y firme su nombre, por ejemplo, "Con amor, Juan y Maria"',
    'RequestedByTitle' => 'Escriba su nombre y mensaje como debe aparecer en el certificado',
    'SpecialInstructionsLabel' => 'Instrucciones especiales no se incluirán en la confirmación',
    'SpecialInstructionsTitle' => 'Instrucciones especiales - opcional',
    'LivingLabel' => 'Marca si es para vivos',
    'DeceasedLabel' => 'Marca si es para fallecidos',
    'SendNotificationLabel' => 'Envíe notificación (o tarjeta si está seleccionada) a otra persona por mí.',
    'NotificationLanguangeLabel' => 'Idioma de notificación',
    'TitleLabel' => 'Título
',
    'FirstNameLabel' => 'Nombre
',
    'LastNameLabel' => 'Apellido
',
    'AddressLabel' => 'Dirección',
    'Address2Label' => 'Dirección 2',
    'CityLabel' => 'Ciudad',
    'CountryLabel' => 'País',
    'StateProvinceLabel' => 'Provincia/Estado',
    'ZipPostalLabel' => 'Código postal',
    'ZipPostalPlaceholder' => 'Código postal',
    'EmailLabel' => 'Email',
    'SupportWithDonationLabel' => 'Me gustaría apoyar con esa donación para las Misas',
    'CountinueLabel' => 'Continua',
    'MassDetailsLabel' => 'Detalles de Misa',
    'OrderSummaryLabel' => 'Resumen del pedido',
    'CardHolderNameLabel' => 'Nombre del titular de la tarjeta',
    'CardNumberLabel' => 'Número de terjeta de credito',
    'CVVLabel' => 'CVV',
    'SameAsContactDetail' => 'Los mismos que en mis datos del contacto',
    'NumberOfMassesLabel' => 'Número de Misas
',
    'NumberOfMassesInfo' => 'El número 9 indicará Novena de misas
',
    'RequestDetailsLabel' => 'Detalles del Pedido',
    'YourIntentionsLabel' => 'Sus intenciones ',
    'YourIntentionsPlaceholder' => 'Enumere sus intenciones',
    'RequestingMassesLabel' => 'Quién solicita misas',
    'RequestingMassesPlaceholder' => 'Por favor, escriba el nombre completo de la persona que solicita misas',
    'DonationAmountLabel' => 'Monto de donación',
    'DonationAmountPlaceholder' => 'Monto de tu donativo (solo se permite el valor numérico)',
    'DeliveryDetailsLabel' => 'Detalles de Entrega',
    'NameLabel' => 'Nombre',
    'SupportWithDonationInfo' => 'Al solicitar misas, inscripción perpetua, etc., usted apoya nuestro ministerio misionero.',
    'HomePhoneLabel' => 'Teléfono de contacto',
    'CellPhoneLabel' => 'Teléfono celular
',
    'BackLabel' => 'Regresar',
    'CancelLabel' => 'Cancelar',
    'ContinueLabel' => 'Continuar',
    'PaymentDetailsTab' => 'Detalles del Pago',
    'NameOfIndividualFamilyLabel' => 'Nombre del individuo/familia',
    'InternationalShippingLabel' => 'Envío internacional',
    'PaymentInformationLabel' => 'Información del pago',
    'CardTypeLabel' => 'Tipo de tarjeta',
    'ExpMonthLabel' => 'Mes de vencimiento',
    'ExpYearLabel' => 'Año de vencimiento',
    'ExpMonthPlaceholder' => 'Mes',
    'ExpYearPlaceholder' => 'Año',
    'CVVPlaceholder' => 'Código de seguridad',
    'BillingDetailsLabel' => 'Detalles de Facturación
',
    'SubmitLabel' => 'Enviar',
    'AddressDetailsLabel' => 'Dirección
',
    'CorrectFollowing' => 'Corrija los siguientes errores antes de continuar:',
    'FirstNameRequrired' => 'El campo "Nombre" es obligatorio.',
    'LastNameRequrired' => 'El campo "Apellido" es obligatorio.',
    'AddressRequired' => 'El campo "Dirección" es obligatorio.',
    'EmailAddressRequrired' => 'El campo "Dirección de correo electrónico" es obligatorio.',
    'EmailAddressInvalid' => 'Correo electrónico no es válido. Asegúrese que su dirección de correo electrónico no tenga caracteres nacionales.
',
    'CityRequired' => 'El campo "Ciudad" es obligatorio',
    'CountryRequired' => 'El campo "País" es obligatorio.
',
    'MessageSuccess' => 'Gracias por tu donación
',
    'InvalidCaptcha' => 'Código Captcha inválido.
',
    'ZipRequired' => 'El campo "Código Postal" es obligatorio',
    'StateRequired' => 'El campo "Estado" es obligatorio',
    'CardHolderNameRequired' => 'El campo "Nombre del titular de la tarjeta" es obligatorio.',
    'CardTypeRequired' => 'El campo "Tipo de tarjeta" es obligatorio.',
    'CardNumberRequired' => 'El campo "Número de tarjeta" es obligatorio.
',
    'ExpiryMonthRequired' => 'El campo "Mes de vencimiento" es obligatorio.',
    'ExpiryYearRequired' => 'El campo "Año de vencimiento" es obligatorio.
',
    'CVVRequired' => 'El campo "CVV" es obligatorio.',
    'NotificationLanguageRequired' => 'El campo "Idioma de notificación" es obligatorio.',
    'SupportWithDonationRequired' => 'El campo "Me gustaría apoyar con esa donación para las Misas" es obligatorio.',
    'card-anthony' => 'San Antonio',
    'card-black-madonna' => 'Ntra. Sra. de Czestochowa
',
    'card-christmas' => 'Navidad
',
    'card-divine-mercy' => 'Divina Misericordia
',
    'card-eucharist' => 'Sagrada Eucaristía
',
    'card-fatima-one' => 'Ntra. Sra. de Fátima
',
    'card-good-shepherd' => 'El Buen Pastor
',
    'card-guadalupe' => 'Ntra. Sra. de Guadalupe
',
    'card-guardian-angel' => 'Santo Angel de la Guarda
',
    'card-heart-jesus' => 'Sdo. Corazón de Jesús
',
    'card-heart-jesus-two' => 'Sdo. Corazón de Jesús (2)
',
    'card-holy-family' => 'Sagrada Familila',
    'card-immaculate-heart' => 'Inmaculado Corazón de María
',
    'card-immaculate-mary-one' => 'María Inmaculada (1)
',
    'card-immaculate-mary-two' => 'María Inmaculada (2)
',
    'card-jesus-children' => 'Jesús con los Niños
',
    'card-jesus-christ' => 'Jesucristo
',
    'card-jesus-garden-one' => 'Oración del Huerto (1)
',
    'card-jesus-garden-two' => 'Oración del Huerto
',
    'card-john-paul-one' => 'Juan Pablo II
',
    'card-john-paul-two' => 'Juan Pablo II (2)
',
    'card-joseph' => 'San José',
    'card-lady-angels' => 'Ntra. Sra. de Los Angeles
',
    'card-lady-fatima-two' => 'Ntra. Sra. de Fátima (2)
',
    'card-lady-street' => 'Ntra. Sra. de las Calles 
',
    'card-mother-help' => 'Ntra. Sra. del Perpetuo Socorro',
    'card-pentecost' => 'Pentecostés',
    'card-pieta' => 'Madre Dolorosa',
    'card-pio' => 'Padre Pio de Pietrelcina',
    'card-resurraction-one' => 'Resurrección (1) 
',
    'card-resurrection-two' => 'Resurrección (2)
',
    'card-sunrise' => 'Amanecer',
    'card-sunset' => 'Atardecer',
    'FlipCard' => 'Dale vuelta',
    'Gold' => 'Oro',
    'Blue' => 'Azul',
    'Red' => 'Rojo',
    'Silver' => 'Plata',
    'White' => 'Blanco',
    'KEYCOLLEGE' => 'Preparación de nuevos misioneros',
    'KEYMISSION' => 'Proyectos en las misiones
',
    'KEYRETIREMENT' => 'Cuidado de misioneros jubilados
',
    'KEYMOSTNEEDED' => 'Donde más se necesita
',
    'PaymentFailed' => 'Pago fallido. Por favor, inténtelo de nuevo más tarde.',
    'NmassRequiredError' => 'El campo "Número de misas" es obligatorio.',
    'IntentionRequiredError' => 'El campo "Sus intenciones" es obligatorio.',
    'WhoReqRequiredError' => 'Se requiere el campo "Quién solicita misas".',
    'DonationRequired' => 'Se requiere el campo "Monto de donación".',
    'LivDecRequiredError' => 'El campo "Vivo/Fallecido" es obligatorio.',
    'ConfirmCancel' => '¿Seguro que quieres cancelar esto? Esta acción no se puede deshacer.',
    'TotalPayment' => 'Gran total',
    'ContactFormSaved' => 'Los datos de contacto se han salvado correctamente. Continúe agregando los detalles de pago a continuación.',
    'EnrollFormSaved' => 'Los detalles de la donación se han salvado correctamente. Continúe agregando los datos de contacto a continuación.',
    'English' => 'Inglés',
    'Polish' => 'Polaco
',
    'Spanish' => 'Español
',
    'Portuguese' => 'Portugués
',
    'French' => 'Francés
',
    'German' => 'Alemán
',
    'Croatian' => 'Croata
',
    'Hungarian' => 'Húngaro',
    'Italian' => 'Italiano',
    'Lithuanian' => 'Lituania',
    'Slovak' => 'Eslovaco',
    'Vietnamese' => 'Vietnamita
',
    'Cebuano' => 'Cebuano',
    'Tagalog' => 'Tagalo',
    'Iloko' => 'Ilocano',
    'Korean' => 'Coreano',
    'SelectYourImage' => 'Selecciona tu imagen',
    'AcceptAndClose' => 'Aceptar y cerrar',
    'CardOptions' => 'Opciones de tarjeta',
    'ActualSize' => 'El tamaño real de la carpeta abierta es de 13 x 8.5 pulgadas',
    'CardImage' => 'Imagen de tarjeta',
    'FolderColor' => 'Color de la carpeta',
    'Baptism' => 'Bautismo',
    'Confirmation' => 'Confirmación',
    'Graduation' => 'Graduación',
    'Birthday' => 'Cumpleaños',
    'RequestedByRequired' => 'El campo "Solicitado por" es obligatorio.',
    'IndividualNameRequired' => 'El campo "Nombre del individuo" es obligatorio.',
    'FamilyNameRequired' => 'El campo "Nombre de la familia" es obligatorio.',
    'NumberOfMassesPlaceholder' => 'Número de misas (solo se permite el valor numérico)',
    'DonateNow' => 'Done ahora
',
    'SearchThisSite' => 'Busca este sitio web',
    'MatchDonorReceiverEmailID' => 'El correo electrónico del donante y del receptor de notificación debe ser diferente.',
    'NumberOfMassesLabelSecondary' => 'La donación por una Santa Misa es de $ 10.00 USD',
    'PrintReceipt' => 'Imprima el recibo',
    'ThankYouforthePayment' => 'Gracias por tu donativo',
    'Areyousureyouwanttosubmittheorder' => '¿Estás seguro de que deseas enviar el pedido?',
    'Cardnumbermustcontainonlydigits' => 'El número de tarjeta debe contener solo dígitos.',
    'TheStateProvincefieldisrequired' => 'El campo "Estado/Provincia" es obligatorio',
    'AtleastoneStateProvinceshouldbeselected' => 'Se debe seleccionar al menos un "Estado/Provincia"',
    'Cardhasexpired' => 'La tarjeta ha caducado',
    'AckFormNoteForCardOption' => 'El tamaño de la tarjeta abierta es de 21,5 x 17,7 cm.',
    'Form2' => 'Alianza Misionera de Misas',
    'Form5' => 'Santas Misas
',
    'Form6' => 'Misas Gregorianas',
    'Form7' => 'Misas por los fallecidos',
    'Form8' => 'Novena de Misas por el día de las Madres',
    'Form9' => 'Misas por los estudiantes',
    'Form10' => 'Misas por los enfermos',
    'Form13' => 'Misas de primero viernes del mes',
    'Jan' => 'ene',
    'Feb' => 'feb',
    'Mar' => 'mar',
    'Apr' => 'abr',
    'May' => 'Mayo',
    'Jun' => 'jun',
    'Jul' => 'jul',
    'Aug' => 'ago',
    'Sep' => 'sep',
    'Oct' => 'oct',
    'Nov' => 'nov',
    'Dec' => 'dic',
    'Month' => 'Mes',
    'GregorianDonation' => 'La donación por 30 Misas Gregorianas es de $400.00',
    'Form1' => 'Alianza Misionera de Misas',
    'Form3' => 'Alianza Misionera de Misas',
    'Form4' => 'Alianza Misionera de Misas',
    'DeceasedPerson' => 'Por favor escriba el nombre completo de una persona fallecida',
    'InternationalCharge' => '$10.00 se agregará automáticamente a los pedidos enviados por correo fuera de los Estados Unidos',
    'livinglabel' => 'Vivos',
    'deceasedlabel' => 'Fallecidos',
    'ViewPreview' => 'Visualizar Certificado',
    'Address3Label' => 'Dirección 3',
    'CheckIfYouWantTheCardOnBehalf' => 'Marque si desea que enviemos la tarjeta en su nombre.',
    'notApplicable' => 'N/A',
    'SelectOccasion' => 'Selecione ocasión',
    'LivingOrDeceased' => 'Vivos o fallecidos',
    'ExpressionofCondolences' => 'Expresión de condolencias',
    'FirstCommunion' => 'Primera comunión',
    'WeddingAnniversary' => 'Aniversario',
    'OtherOccasion' => 'Otra ocasión',
    'or' => '- O -',
    'SupportWithDonationPlaceholder' => 'Seleccione aquí lo que le gustaría apoyar con esta donación para misas.',
    'ContactDetailsHeader' => 'Contacto',
    'Yes' => 'Si',
    'No' => 'No',
    'Form11' => ' Novena a la Divina Misericordia',
    'Form12' => 'Novena del Día del Padre',
    'ExpressionOfCondolences' => 'Expresión de condolencias',
    'paymentButtonText' => 'PAGAR',
    'paymentInstructionText' => 'Entre el número de tarjeta, la fecha de vencimiento (mes/año) y el código de seguridad.',
    'DoubleClickMessage' => 'Después de hacer clic en ENVIAR y agregar la información de su tarjeta de crédito, haga clic en PAGAR y espere su recibo. No haga clic en PAGAR por segunda vez.',
];
