<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-04-22T01:44:38-05:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      paymentInstructionText
 * @group     vi
 * @namespace mass_enrollment
 * -----------------------------------------------------------------------------
 */
return [
    'ContactDetailsTab' => 'tài liệu liên lạc của tôi',
    'DonationDetailsTab' => 'Chi tiết đóng góp
',
    'OcassionLabel' => 'Nhân dịp
',
    'FolderDetailsLabel' => 'Chi tiết thư mục / thẻ',
    'SelectImageLabel' => 'Chọn hình ảnh',
    'SelectFolderColorLabel' => 'Chọn màu thư mục',
    'LanguageLabel' => 'Ngôn ngữ',
    'LanguageSelectLabel' => 'Chọn tiếng
',
    'RequestedByLabel' => 'Tên người xin',
    'OccasionRequiredError' => 'Trường "Nhân dịp" là bắt buộc.',
    'EnrollmentDetailsTitle' => 'Chi tiết tuyển sinh',
    'EnrollmentTypeTitle' => 'Loại tuyển sinh',
    'EnrollmentDateLabel' => 'Ngày ghi danh',
    'FamilyPriceLabel' => 'gia đình',
    'IndividualPriceLabel' => 'Cá nhân',
    'IndividualTextTitle' => 'Xin vui lòng liệt kê tên người ghi danh',
    'IndividualEnrollNamePlaceholder' => 'tên mỗi cá nhân',
    'OutOFLabel' => 'ra khỏi',
    'CharacterLabel' => 'nhân vật',
    'FamilyEnrollNameTitle' => 'Xin vui lòng liệt kê tên họ của gia đình,  (ví dụ như gia đình họ Nguyễn, hoặc liệt kê tên của mỗi thành viên trong gia đình được tách ra bởi dấu phẩy',
    'FamiliyEnrollNamePlaceholder' => 'tên họ của gia đình',
    'RequestedByInfo' => 'viết đôi dòng nhắn tin, sau đó ký tên',
    'RequestedByTitle' => 'Viết tên và thông điệp của bạn muốn có trên trên chứng chỉ',
    'SpecialInstructionsLabel' => 'Hướng dẫn đặc biệt',
    'SpecialInstructionsTitle' => 'Hướng dẫn đặc biệt (tùy ý- sẽ không đăng tải trên bằng hoặc giấy chứng nhận)',
    'LivingLabel' => 'Cuộc sống',
    'DeceasedLabel' => 'Người chết',
    'SendNotificationLabel' => 'Gửi thông báo (hoặc bằng) cho người khác thay tôi.',
    'NotificationLanguangeLabel' => 'ngôn ngữ thông báo',
    'TitleLabel' => 'Chức vụ
',
    'FirstNameLabel' => 'Tên gọi
',
    'LastNameLabel' => 'Tên họ
',
    'AddressLabel' => 'Địa chỉ
',
    'Address2Label' => 'Địa chỉ hai
',
    'CityLabel' => 'Thành phố
',
    'CountryLabel' => 'Quốc gia
',
    'StateProvinceLabel' => 'Bang / tỉnh
',
    'ZipPostalLabel' => 'Mã bưu chính / mã bưu điện
',
    'ZipPostalPlaceholder' => 'Mã bưu chính / mã bưu điện
',
    'EmailLabel' => 'E-mail
',
    'SupportWithDonationLabel' => 'Lý do yêu cầu về sự đóng góp của quí vị',
    'CountinueLabel' => 'Tiếp tục',
    'MassDetailsLabel' => 'Chi tiết đại chúng',
    'NumberOfMassesLabel' => 'Số Lễ',
    'NumberOfMassesInfo' => 'theo phong tục đóng góp $10.00 cho mỗi thánh lễ',
    'RequestDetailsLabel' => 'Yêu cầu chi tiết',
    'YourIntentionsLabel' => 'Ý xin của bạn',
    'YourIntentionsPlaceholder' => 'liệt kê ý xin',
    'RequestingMassesLabel' => 'Họ và tên của người xin',
    'RequestingMassesPlaceholder' => 'Vui lòng viết tên đầy đủ của người yêu cầu Thánh Lễ',
    'DonationAmountLabel' => 'Số tiền quyên góp',
    'DonationAmountPlaceholder' => 'Số tiền (Chỉ cho phép giá trị số)',
    'DeliveryDetailsLabel' => 'Chi tiết giao hàng',
    'NameLabel' => 'Tên',
    'HomePhoneLabel' => 'Điện thoại liên hệ',
    'CellPhoneLabel' => 'Điện thoại di động',
    'BackLabel' => 'Trở lại',
    'CancelLabel' => 'Hủy bỏ',
    'ContinueLabel' => 'Tiếp tục',
    'PaymentDetailsTab' => 'Chi tiết thanh toán',
    'OrderSummaryLabel' => 'Tóm tắt theo thứ tự',
    'NameOfIndividualFamilyLabel' => 'Tên của cá nhân / gia đình',
    'InternationalShippingLabel' => 'Vận chuyển quốc tế',
    'PaymentInformationLabel' => 'Thông tin thanh toán',
    'CardHolderNameLabel' => 'Tên chủ thẻ',
    'CardTypeLabel' => 'Loại thẻ',
    'CardNumberLabel' => 'Số thẻ',
    'ExpMonthLabel' => 'Tháng hết hạn',
    'ExpYearLabel' => 'Năm hết hạn',
    'ExpMonthPlaceholder' => 'tháng',
    'ExpYearPlaceholder' => 'Năm',
    'CVVLabel' => 'CVV',
    'CVVPlaceholder' => 'Mã bảo mật
',
    'BillingDetailsLabel' => 'Chi tiết thanh toán',
    'SameAsContactDetail' => 'Tương tự như chi tiết liên lạc',
    'SubmitLabel' => 'Gửi đi',
    'AddressDetailsLabel' => 'Chi tiết địa chỉ',
    'CorrectFollowing' => 'Vui lòng sửa các lỗi sau trước khi tiếp tục:',
    'FirstNameRequrired' => 'Trường "Tên" là bắt buộc.',
    'LastNameRequrired' => 'Trường "Họ" là bắt buộc.',
    'AddressRequired' => 'Trường "Địa chỉ" là bắt buộc.',
    'EmailAddressRequrired' => 'Trường "Địa chỉ Email" là bắt buộc.',
    'EmailAddressInvalid' => 'Địa chỉ email inavlid.',
    'CityRequired' => 'Trường "Thành phố" là bắt buộc',
    'CountryRequired' => 'Trường "Quốc gia" là bắt buộc.',
    'MessageSuccess' => 'Cảm ơn bạn đã gửi.',
    'InvalidCaptcha' => 'Mã xác thực không hợp lệ.',
    'ZipRequired' => 'Trường "Zip / Post" là bắt buộc',
    'StateRequired' => 'Trường "Nhà nước" là bắt buộc',
    'CardHolderNameRequired' => 'Trường "Tên chủ thẻ" là bắt buộc.',
    'CardTypeRequired' => 'Trường "Loại thẻ" là bắt buộc.',
    'CardNumberRequired' => 'Trường "Số thẻ" là bắt buộc.',
    'ExpiryMonthRequired' => 'Trường "Tháng hết hạn" là bắt buộc.',
    'ExpiryYearRequired' => 'Trường "Năm hết hạn" là bắt buộc.',
    'CVVRequired' => 'Trường "CVV" là bắt buộc.',
    'NotificationLanguageRequired' => 'Trường "Ngôn ngữ thông báo" là bắt buộc.',
    'SupportWithDonationRequired' => 'Vui lòng chọn những gì bạn muốn hỗ trợ với đóng góp của bạn.',
    'card-black-madonna' => 'Đức Mẹ Czeztochova
',
    'card-christmas' => 'Lễ Sinh Nhật
',
    'card-divine-mercy' => 'Lòng Thương Xót
',
    'card-eucharist' => 'Thánh Thể
',
    'card-fatima-one' => 'Đức Mẹ Fátima (lễ canh thức)
',
    'card-good-shepherd' => 'Mục Từ Nhân Lành
',
    'card-guadalupe' => 'Đức Mẹ Guadalupe
',
    'card-guardian-angel' => 'Thiên Thần Bổn Mệnh
',
    'card-heart-jesus' => 'Thánh Tâm Chúa Giêsu (lễ canh thức)
',
    'card-heart-jesus-two' => 'Thánh Tâm Chúa Giêsu (lễ chính)
',
    'card-holy-family' => 'Gia Đình Thánh Gia
',
    'card-immaculate-heart' => 'Trái Tim Vẹn Sạch Đức Mẹ Maria
',
    'card-immaculate-mary-one' => 'Maria Vô Nhiễm Nguyên Tội (lễ canh thức)
',
    'card-immaculate-mary-two' => 'Maria Vô Nhiễm Nguyên Tội (lễ chính)
',
    'card-jesus-children' => 'Chúa Giêsu và các em nhỏ
',
    'card-jesus-christ' => 'Giêsu
',
    'card-jesus-garden-one' => 'Lời cầu nguyện trong Vườn Ghếtsêmani (lễ canh thức)
',
    'card-jesus-garden-two' => 'Lời cầu nguyện trong Vườn Ghếtsêmani (lễ chính)
',
    'card-john-paul-one' => 'Gioan Phaolô II  (lễ canh thức)
',
    'card-john-paul-two' => 'Gioan Phaolô II (lễ chính)
',
    'card-joseph' => 'Thánh cả Guise
',
    'card-lady-angels' => 'Nữ Vương Các Thiên Thần
',
    'card-lady-fatima-two' => 'Đức Mẹ Fátima (lễ chính)
',
    'card-lady-street' => 'Nữ Vương Các Phố Phường
',
    'card-mother-help' => 'Đức Mẹ Hằng Cứu Giúp
',
    'card-pentecost' => 'Lễ Ngũ Tuần
',
    'card-pieta' => 'Đức Mẹ Sầu Bi
',
    'card-pio' => 'Thánh Pio
',
    'card-resurraction-one' => 'Phục Sinh (Lễ Vọng)
',
    'card-resurrection-two' => 'Phục sinh (Lễ Chính)
',
    'card-sunrise' => 'Hừng Đông
',
    'card-sunset' => 'Chiều Tàn
',
    'FlipCard' => 'Thẻ lật',
    'SelectYourImage' => 'Chọn hình ảnh của bạn',
    'AcceptAndClose' => 'Chấp nhận và đóng',
    'CardOptions' => 'Tùy chọn thẻ',
    'ActualSize' => 'Kích thước thực tế của thư mục mở là 13 x 8,5 inch',
    'CardImage' => 'Hình ảnh thẻ',
    'FolderColor' => 'Màu thư mục',
    'Gold' => 'Vàng',
    'Blue' => 'Màu xanh',
    'Red' => 'Màu đỏ
',
    'Silver' => 'Bạc',
    'White' => 'Trắng',
    'Baptism' => 'Rửa tội',
    'Confirmation' => 'Xác nhận',
    'Graduation' => 'Tốt nghiệp',
    'Birthday' => 'Sinh nhật',
    'RequestedByRequired' => '"Được yêu cầu bởi" là một trường bắt buộc.',
    'IndividualNameRequired' => '"Tên của cá nhân" là một trường bắt buộc.',
    'FamilyNameRequired' => '"Tên của gia đình" là một trường bắt buộc.',
    'KEYCOLLEGE' => 'Chuẩn bị truyền giáo mới tại Divine Word College
',
    'KEYMISSION' => 'Dự án truyền giáo
',
    'KEYRETIREMENT' => 'Chăm sóc cho các nhà truyền giáo đã nghỉ hưu
',
    'KEYMOSTNEEDED' => 'Nơi cần thiết nhất
',
    'PaymentFailed' => 'Thanh toán không thành công. Vui lòng thử lại sau.',
    'NmassRequiredError' => 'Trường "Số lượng lớn" là bắt buộc.',
    'IntentionRequiredError' => 'Trường "Ý định của bạn" là bắt buộc.',
    'WhoReqRequiredError' => 'Trường "Ai đang yêu cầu Thánh Lễ" là bắt buộc.',
    'DonationRequired' => 'Trường "Số tiền quyên góp" là bắt buộc.',
    'LivDecRequiredError' => 'Trường "Sống / Đã chết" là bắt buộc.',
    'ConfirmCancel' => 'Bạn có chắc chắn muốn hủy bỏ điều này? Hành động này không thể được hoàn tác.',
    'TotalPayment' => 'Tổng cộng',
    'ContactFormSaved' => 'Các chi tiết liên lạc đã được lưu thành công. Vui lòng tiếp tục thêm các chi tiết thanh toán dưới đây.',
    'EnrollFormSaved' => 'Các chi tiết đóng góp đã được lưu thành công. Vui lòng tiếp tục thêm các chi tiết liên lạc dưới đây.',
    'English' => 'Tiếng anh',
    'Polish' => 'Ba Lan
',
    'Spanish' => 'Tây Ban Nha
',
    'Portuguese' => 'Bồ Đào Nha
',
    'French' => 'Tiếng pháp
',
    'German' => 'Tiếng Đức
',
    'Croatian' => 'Tiếng Croatia
',
    'Hungarian' => 'Tiếng Hungary
',
    'Italian' => 'Ý
',
    'Lithuanian' => 'Litva',
    'Slovak' => 'Tiếng Slovak
',
    'Vietnamese' => 'Tiếng việt nam
',
    'Cebuano' => 'Cebuano',
    'Tagalog' => 'Tag Tag
',
    'Iloko' => 'Ilocano',
    'Korean' => 'Tiếng hàn
',
    'NumberOfMassesPlaceholder' => 'Số Lễ (Chỉ cho phép giá trị số)',
    'SupportWithDonationInfo' => 'Yêu cầu Thánh lễ, Ghi danh vĩnh viễn, vv bạn ủng hộ mục vụ truyền giáo của chúng tôi.',
    'PrintReceipt' => 'Biên lai in',
    'ThankYouforthePayment' => 'Cảm ơn bạn đã thanh toán',
    'Areyousureyouwanttosubmittheorder' => 'Bạn có chắc chắn muốn gửi đơn đặt hàng?',
    'AckFormNoteForCardOption' => '* Hình ảnh được chọn sẽ được hiển thị trên bìa trước của thẻ thực tế.',
    'card-anthony' => 'Thẻ Anthony',
    'SearchThisSite' => 'Tìm kiếm trang web này',
    'Cardnumbermustcontainonlydigits' => 'Số thẻ chỉ được chứa các chữ số.',
    'TheStateProvincefieldisrequired' => 'Trường "Bang / Tỉnh" là bắt buộc',
    'AtleastoneStateProvinceshouldbeselected' => 'Ít nhất một "Bang / Tỉnh" phải được chọn',
    'Cardhasexpired' => 'Thẻ đã hết hạn.',
    'MatchDonorReceiverEmailID' => 'Nhà tài trợ và người nhận Email nên khác nhau.',
    'NumberOfMassesLabelSecondary' => 'Đóng góp thông thường $ 10 mỗi khối',
    'DonateNow' => 'Quyên góp',
    'GregorianDonation' => 'Quyên góp cho tất cả 30 Thánh lễ Gregorian là $ 400.00',
    'Form1' => 'Mission Mass League',
    'Form2' => 'Mission Mass League',
    'Form3' => 'Mission Mass League',
    'Form4' => 'Mission Mass League',
    'Form5' => 'Holy Masses',
    'Form6' => 'Gregorian Masses',
    'Form7' => 'All Souls Novena of Masses',
    'Form8' => 'Mother\'s Day Novena of Masses',
    'Form9' => 'Masses for school children and students',
    'Form10' => 'Masses for sick',
    'DeceasedPerson' => 'Vui lòng viết tên đầy đủ của một người đã chết',
    'InternationalCharge' => '$10.00 sẽ được thêm tự động vào các đơn đặt hàng được gửi bên ngoài Hoa Kỳ',
    'deceasedlabel' => 'Người chết',
    'livinglabel' => 'Cuộc sống',
    'ViewPreview' => 'Xem bản xem trước',
    'Address3Label' => 'địa chỉ 3',
    'CheckIfYouWantTheCardOnBehalf' => 'Kiểm tra nếu bạn muốn chúng tôi gửi thẻ thay mặt bạn.',
    'notApplicable' => 'Không có',
    'ExpressionofCondolences' => 'Biểu hiện chia buồn',
    'FirstCommunion' => 'Hiệp thông đầu tiên',
    'WeddingAnniversary' => 'Kỷ niệm ngày cưới',
    'OtherOccasion' => 'Dịp khác',
    'SelectOccasion' => 'Chọn dịp',
    'LivingOrDeceased' => 'Sống hoặc chết',
    'paymentButtonText' => 'TRẢ',
    'paymentInstructionText' => 'Nhập thông tin thẻ',
];
