<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-02-05T09:34:04-06:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      MessageSuccess
 * @group     pl
 * @namespace prayer_corner
 * -----------------------------------------------------------------------------
 */
return [
    'CorrectFollowing' => 'Przed kontynuowaniem popraw następujące błędy:',
    'FirstName' => 'Imię',
    'FirstNameRequrired' => 'Pole „Imię” jest wymagane.',
    'LastName' => 'Nazwisko',
    'LastNameRequrired' => 'Pole „Nazwisko” jest wymagane.',
    'LastNameExtra' => 'Nie zostanie dodane do kącika modlitewnego.',
    'EmailAddress' => 'Adres e-mail',
    'EmailAddressExtra' => 'Skontaktujemy się z Tobą tylko wtedy, gdy wyrazisz na to zgodę, a Twój adres e-mail zostanie wykorzystany do uwierzytelnienia, aby upewnić się, że kontaktuje się z nami prawdziwa osoba.',
    'EmailAddressRequrired' => 'Pole „Adres e-mail” jest wymagane.',
    'EmailAddressInvalid' => 'Nieznany adres e-mail.',
    'City' => 'Miasto',
    'Country' => 'Kraj',
    'PrayerRequest' => 'Prośba o modlitwę',
    'PrayerRequestRequrired' => 'Pole „Prośba o modlitwę” jest wymagane.',
    'PostPublicCheckbox' => 'Dodaj moją prośbę do kącika modlitewnego (jeżeli wybierzesz tę opcje to potwierdzasz, że wyrażasz zgodę na opublikowanie swojej prośby na tej stronie)',
    'ConsentCheckbox' => 'Wyrażam zgodę na kontakt ze mną za pośrednictwem poczty elektronicznej.',
    'PolicyLabel' => 'Polityka użytkownika',
    'SubmitLabel' => 'Wyślij swoją prośbę',
    'MessageSuccess' => 'Dziękujemy za przesłanie prośby o modlitwę',
    'InvalidCaptcha' => 'Nieprawidłowy kod CAPTCHA.',
    'PolicyTitle' => 'Monitorujemy komentarze i usuniemy posty zawierające następujące elementy:',
    'PolicyPoint1' => 'Hiperłącza, reklamy lub inne treści podobne do spamu',
    'PolicyPoint2' => 'Treści, które uznamy za nieodpowiednie, obraźliwe lub poniżające',
    'PolicyPoint3' => 'Wulgaryzmy, oskarżycielski i zapalny język',
    'PolicyPoint4' => 'Komentarze przedstawiające konkretny program polityczny',
    'PolicyPoint5' => 'Obraźliwe lub poniżające komentarze odnośnie innych kultur i religii',
    'SelectCountry' => 'Wybierz kraj',
];
