<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-02-25T18:28:26-06:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      SelectCountry
 * @group     po
 * @namespace prayer_corner
 * -----------------------------------------------------------------------------
 */
return [
    'CorrectFollowing' => 'Corrija os seguintes erros antes de continuar:',
    'FirstName' => 'Nome',
    'FirstNameRequrired' => 'O campo "Nome" é obrigatório.',
    'LastName' => 'Sobrenome',
    'LastNameRequrired' => 'O campo "Sobrenome" é obrigatório.',
    'LastNameExtra' => 'Não será adicionado ao mural de oração.',
    'EmailAddress' => 'Endereço de e-mail',
    'EmailAddressExtra' => 'Entraremos em contacto somente se nos der permissão e o seu e-mail  irá ser usado para autenticação, garantindo que estamos a ser contactados por uma pessoa real.',
    'EmailAddressRequrired' => 'O campo "Endereço de e-mail" é obrigatório.',
    'EmailAddressInvalid' => 'Endereço de e-mail inválido.',
    'City' => 'Cidade',
    'Country' => 'País',
    'PrayerRequest' => 'Pedido de oração',
    'PrayerRequestRequrired' => 'O campo "Pedido de oração" é obrigatório.',
    'PostPublicCheckbox' => 'Adicione ao mural de oração (se fizer isso, estará a dar permissão para publicar o seu pedido de oração neste site).',
    'ConsentCheckbox' => 'Autorizo o Verbo Divino a entrar em contacto comigo por e-mail.',
    'PolicyLabel' => 'Política',
    'SubmitLabel' => 'Envie a sua solicitação',
    'MessageSuccess' => 'Obrigado por enviar-nos o seu pedido de oração.',
    'InvalidCaptcha' => 'Código Captcha inválido.',
    'PolicyTitle' => 'Monitoramos os comentários e removeremos os pedidos que contêm o seguinte:',
    'PolicyPoint1' => 'Hiperlinks, anúncios ou outro conteúdo semelhante a spam',
    'PolicyPoint2' => 'Conteúdo que julgamos inapropriado, ofensivo ou degradante',
    'PolicyPoint3' => 'Profanação, linguagem acusatória e inflamatória',
    'PolicyPoint4' => 'Comentários que apresentam uma agenda política específica',
    'PolicyPoint5' => 'Comentários ofensivos ou humilhantes a outras culturas e religiões',
    'SelectCountry' => 'Seleccione o país',
];
