<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-02-08T14:38:00-06:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      MessageSuccess
 * @group     sp
 * @namespace prayer_corner
 * -----------------------------------------------------------------------------
 */
return [
    'CorrectFollowing' => 'Corrija los siguientes errores antes de continuar:',
    'FirstName' => 'Nombre',
    'FirstNameRequrired' => 'El campo "Nombre" es obligatorio.',
    'LastName' => 'Apellido',
    'LastNameRequrired' => 'El campo "Apellido" es obligatorio.',
    'LastNameExtra' => 'No se agregará al muro de oración.',
    'EmailAddress' => 'Dirección de correo electrónico',
    'EmailAddressExtra' => 'Nos pondremos en contacto con usted solo si nos da permiso y su correo electrónico se utilizará para la autenticación para garantizar que nos contactemos con una persona real.',
    'EmailAddressRequrired' => 'El campo "Dirección de correo electrónico" es obligatorio.',
    'EmailAddressInvalid' => 'Dirección de correo electrónico no es válida',
    'City' => 'Ciudad',
    'Country' => 'País',
    'PrayerRequest' => 'Petición de oración',
    'PrayerRequestRequrired' => 'El campo "Petición de oración" es obligatorio.',
    'PostPublicCheckbox' => 'Publique en el Muro de Oración (escogiendo esa opción, está autorizándonos para publicar su oración en este sitio web)',
    'ConsentCheckbox' => 'Doy mi consentimiento para que los Misioneros del Verbo Divino se comuniquen conmigo por correo electrónico.',
    'PolicyLabel' => 'Política',
    'SubmitLabel' => 'Solicita la oración',
    'MessageSuccess' => 'Gracias por tu pedido de oración.',
    'InvalidCaptcha' => 'Código Captcha inválido.',
    'PolicyTitle' => 'Hacemos un sondeo de los comentarios y eliminaremos las publicaciones que contengan lo siguiente:',
    'PolicyPoint1' => 'Hipervínculos, anuncios u otro contenido similar al spam',
    'PolicyPoint2' => 'Contenido que consideramos inapropiado, ofensivo o degradante',
    'PolicyPoint3' => 'Lenguaje profano, acusatorio e inflamatorio',
    'PolicyPoint4' => 'Comentarios que presentan una específica agenda política ',
    'PolicyPoint5' => 'Comentarios ofensivos o degradantes hacia otras culturas y religiones',
    'SelectCountry' => 'Seleccionar país',
];
