<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-11-12T05:55:02-06:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      SelectCountry
 * @group     vi
 * @namespace prayer_corner
 * -----------------------------------------------------------------------------
 */
return [
    'CorrectFollowing' => 'Vui lòng sửa các lỗi sau trước khi tiếp tục:',
    'FirstName' => 'Tên đầu tiên',
    'FirstNameRequrired' => 'Trường "Tên" là bắt buộc.',
    'LastName' => 'Họ',
    'LastNameRequrired' => 'Trường "Họ" là bắt buộc.',
    'LastNameExtra' => 'Sẽ không được thêm vào tường cầu nguyện.',
    'EmailAddress' => 'Địa chỉ email',
    'EmailAddressExtra' => 'Chúng tôi sẽ chỉ liên hệ với bạn nếu bạn cho phép chúng tôi và email của bạn sẽ được sử dụng để xác thực để đảm bảo rằng chúng tôi được liên hệ bởi người thật.',
    'EmailAddressRequrired' => 'Trường "Địa chỉ Email" là bắt buộc.',
    'EmailAddressInvalid' => 'Địa chỉ email inavlid.',
    'City' => 'Thành phố',
    'Country' => 'Quốc gia',
    'PrayerRequest' => 'Yêu cầu cầu nguyện',
    'PrayerRequestRequrired' => 'Trường "Yêu cầu cầu nguyện" là bắt buộc.',
    'PostPublicCheckbox' => 'Đăng lên Tường cầu nguyện công khai (Nếu bạn đang đăng lên tường cầu nguyện, bạn thừa nhận rằng bạn đang cho phép đăng lời cầu nguyện của bạn trên trang web này)',
    'ConsentCheckbox' => 'Tôi đồng ý cho Hiệp hội Lời Chúa liên lạc với tôi qua email.',
    'PolicyLabel' => 'Chính sách',
    'SubmitLabel' => 'Gửi yêu cầu của bạn',
    'MessageSuccess' => 'Cảm ơn bạn đã gửi.',
    'InvalidCaptcha' => 'Mã xác thực không hợp lệ.',
    'PolicyTitle' => 'Chúng tôi theo dõi các bình luận và sẽ xóa các bài đăng có chứa thông tin sau:',
    'PolicyPoint1' => 'Siêu liên kết, quảng cáo hoặc nội dung giống như thư rác',
    'PolicyPoint2' => 'Nội dung chúng tôi cho là không phù hợp, gây khó chịu hoặc hạ thấp',
    'PolicyPoint3' => 'Nói tục tĩu, buộc tội, ngôn ngữ viêm',
    'PolicyPoint4' => 'Bình luận trình bày một chương trình nghị sự chính trị cụ thể',
    'PolicyPoint5' => 'Bình luận xúc phạm hoặc hạ thấp đối với các nền văn hóa và tôn giáo khác',
    'SelectCountry' => 'Chọn quốc gia',
];
